### PR TITLE
Fix "make check" -Wsign-compare on arm32 broken by 1a51cf7

### PR DESCRIPTION
**Pull request by rousskov**
MemBuf::contentSize() returns mb_size_t which is signed.

### CODE REVIEW

**Comment by rousskov** [comment]
Disclaimer: This fix is untested by me.

**Comment by rousskov** [comment]
The bug was reported by Francesco at https://github.com/squid-cache/squid/pull/886#issuecomment-903173518

**Comment by kinkie** [comment]
Hand-testing on arm32

**Comment by kinkie** [comment]
Confirmed working. Thanks for fixing this!

**Review by kinkie — APPROVED** [review]
tested working on arm32

**Comment by kinkie** [comment]
@yadij , could you stamp for fast tracking?

**Comment by rousskov** [comment]
@kinkie, FYI: two core developer votes are enough to fast-track. This PR has been approved by you (explicitly) and me (implicitly, by authoring it). The PR is on the fast track already, and more votes will not make it go any faster. This status is reflected in the "PR approval" check currently shown by GitHub as `waiting for fast track objections`.

**Pull request closed without merging**
