### PR TITLE
Bug 5343: Fix GCC v14 not finding std::find()

### PR DESCRIPTION
**Pull request by kinkie**
Reply.cc:198: error: no matching function for call to find(...)

The required STL header was missed in 2023 commit 27c3677.

### CODE REVIEW

**Comment by yadij** [comment]
I have `InstanceId` fix testing now. No need to hold these PRs for it.

**Review by yadij — APPROVED** [review]

**Comment by uhliarik** [comment]
> I have `InstanceId` fix testing now. No need to hold these PRs for it.

Hey Yadi, it was meanwhile reported as alleged g++ bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113908

**Review by rousskov — APPROVED** [review]
Thank you for completing this work. In the future, please commit additional changes to the original PR branch instead of closing and opening PRs.

I have adjusted PR title to use a more common format, especially since it is not yet clear whether there will ever be a "part 2" fix for this bug. I have also adjusted PR description to fix formatting (by copying #1670 description).

**Comment by kinkie** [comment]
> Thank you for completing this work. In the future, please commit additional changes to the original PR branch instead of closing and opening PRs.

I don't have write access to that branch; that was my first attempt in fact.

> I have adjusted PR title to use a more common format, especially since it is not yet clear whether there will ever be a "part 2" fix for this bug. I have also adjusted PR description to fix formatting (by copying #1670 description).

Thanks!

**Pull request closed without merging**
