### PR TITLE
Source Format Enforcement

### PR DESCRIPTION
**Pull request by squidadm**
Besides routine formatting enforcement, this change contains flag-day
updates and code polishing from code removals performed in the latter
half of 2021 (e.g., HERE removal).

(summary) log from the script execution:

 UPDATE COPYRIGHT for ...
 NOTICE: File ... changed: by scripts/maintenance/HERE-obsolete
 NOTICE: File src/Makefile.am changed: by
   scripts/format-makefile-am.pl
 NOTICE: File src/sbuf/Stream.h changed: by
   scripts/maintenance/sort-includes.pl
 NOTICE: File src/tests/stub_store_client.cc changed: by
   scripts/maintenance/sort-includes.pl

If you are worried about hitting all this at once when rebasing a
 large patch you can split the rebase into steps as follows:

    git fetch --all
    git rebase [ commit ID prior to this one ]
    git rebase [ this commit's ID ]
    git rebase master

### CODE REVIEW

**Comment by yadij** [comment]
OK to test

**Review by yadij — APPROVED** [review]

**Comment by yadij** [comment]
FYI; this is automated output of ./scripts/source-maintenance.sh run on the master release server.

You should be able to replicate the patch on any other machine by running that script yourself on the relevant Squid-6 commit ID checkout. Though caveat then is that you have the same astyle, auto-tools and (missing) gperf versions as the master server.

**Review by rousskov — COMMENTED** [review]
> rousskov self-requested a review

> Amos: FYI; this is automated output of ./scripts/source-maintenance.sh run on the master release server.

I hope so, but, last year, a similar "automated" PR had secret manual changes that had to be removed: https://github.com/squid-cache/squid/pull/763#pullrequestreview-579397331. This year, while I was not going to double check everything, I still wanted to at least look through the changes, just in case. I am glad I did because the diff informed me about the `HERE` removal in this PR! I think that important event should be explicitly disclosed in the PR description. I edited the description to mention it, but you may need to adjust the description further because I do not know what "flag-day updates" and "code polishing from code removals performed in the latter half of 2021" actually means.

It is unfortunate that this PR combines copyright year changes, `HERE` removal, and routine formatting changes because such combination complicates review and merge conflict resolution. However, I am not going to insist on a split.

As you know, I think we should not update copyright years every year, but I see no reason to repeat that last year [discussion](https://github.com/squid-cache/squid/pull/763#pullrequestreview-579383507) this year.

**Comment by rousskov** [comment]
@yadij, please apply the same `HERE` removal script to v5 (while keeping the `HERE` macro defined). We should not create such a huge (in surface area) but empty (in functionality changes) long-term difference between v5 and master/v6 IMO.

**Comment by yadij** [comment]
Okay. I will do that in the 5.4.1 version.

**Pull request closed without merging**
