### PR TITLE
WIP: Cleanup log bufs

### PR DESCRIPTION
**Pull request by yadij**
Update the C-style code for daemon logging module buffers to
C++11 syntax more compliant with current coding guidelines and
drop use of dlink list.

TODO:
 * try replacing logfile_buffer_t with SBuf of pre-reserved size
 * integrate buffer limits with access_log buffer-size=N value

### CODE REVIEW

**Comment by rousskov** [comment]
Posting official draft PRs is meant for asking questions. What questions do you want to ask?

**Comment by yadij** [comment]
> Posting official draft PRs is meant for asking questions.

First I've heard of that. Where does it come from?

> What questions do you want to ask?

In general, just feedback.  I'm posting these all so you can see which directions my work is heading, but I am not certain it is ready for merge review just yet. If you think it at a good stage to polish and merge, or if the design has major issues I'd appreciate the input now rather than after a lot more work.

**Comment by rousskov** [comment]
> First I've heard of that.

Not really: The same principle was explicitly stated during a PR 594 [discussion](https://github.com/squid-cache/squid/pull/594#issuecomment-610481979) and strongly implied in a PR 703 [discussion](https://github.com/squid-cache/squid/pull/703#pullrequestreview-460877655) (at least).

> Where does it come from?

AFAICT, this principle comes from basic logic and the assumption of good intentions: Why would somebody post a PR (which naturally creates work for others) unless they either want to merge it (not applicable to WIP/draft PRs) or need some kind of help/feedback from others? And if no questions are asked, then how would those others would know what kind of feedback the author of a draft PR is looking for, what alternatives they are considering, what decisions are already firmly set, etc.?

> I'm posting these all so you can see which directions my work is heading [...] If you think it at a good stage to polish and merge, or if the design has major issues I'd appreciate the input now rather than after a lot more work.

This PR "updates the C-style code for [...] buffers to C++11 syntax". Without specific questions, choices, concerns, etc., it is very difficult for me to guess what kind of _direction_ you want me to review, what your concerns are, what other options are on the table. It takes significant amount of time for me to properly review PRs. Posting draft PRs without specific questions/concerns increases those overheads. Said that, I will do my best to understand what is needed here and do the right thing, as usual.

**Review by rousskov — CHANGES_REQUESTED** [review]
A few const/auto improvements are probably possible on modified lines, but I do not insist on those.

Disclaimer: I have not reviewed the low-level changes.

**Comment by yadij** [comment]
Abandoned

**Pull request closed without merging**
