### PR TITLE
Improved handling of cachemgr.cgi parameters

### PR DESCRIPTION
**Pull request by aaron-costello**
Increased browser safety for those that support this header.

### CODE REVIEW

**Comment by yadij** [comment]
I do not think this is a good solution to the problem of parameter handling. The header relies on additional configuration at multiple places - at least the client browser settings are vital to it having any effect at all and outside the control of any interested admin.

**Comment by aaron-costello** [comment]
@yadij I understand that viewpoint. However, there continues to be XSS issues affecting the cachemgr.cgi as the previous fixes weren't sufficient. I do not have experience with advanced filtering HTML characters appropriately in C/CPP, but a revision of the fixes in [429](https://github.com/squid-cache/squid/pull/429) is needed as it is by passable.

**Comment by yadij** [comment]
That PR 429 was scoped to the authentication credentials, it is not relevant to any others. If XSS issues remain elsewhere we need them to be fixed, not simply hidden from view.

FYI: The cachemgr reports may contain arbitrary URLs, snippets of object contents from cache, or be replaced in whole with proxy error pages containing dynamic scripts and links to objects in the proxy origin rather than the CGI origin. So approaches like this header that universally prevent these features working are going to break some subset of working installation.

I will followup to the email thread with a suggestion about the parameter you mentioned already. If you have found others, please mention them in the thread and we can look at each as a separate case.

**Comment by aaron-costello** [comment]
In that case since the other parameters appear to be sanitized effectively, it would be simplest to remove the verbose error that's being displayed. I believe "Unknown Host" is a clear enough error without reflecting the parameter too.

**Pull request closed without merging**
