### PR TITLE
V5 next backports

### PR DESCRIPTION
**Pull request by squidadm**

### CODE REVIEW

**Comment by yadij** [comment]
OK to test

**Comment by yadij** [comment]
> There should be no need for this PR because these master commits will be in v5 automatically when v5 is officially branched off master.

Branching has already happened.

**Comment by rousskov** [comment]
@yadij, you have committed a PR that I have blocked. I have been ignoring your insults in reviews, but this official repository modification is crossing the line even for me. If you want to preserve the integrity of the Project, you must stop ignoring the fundamental integrity protections we have in place.

**Comment by yadij** [comment]
What insults have I been directing at you?

All I see in regards to insults in PRs are messages like the one above attacking my actions, decisions as a developer in proposals or use of QA powers to prevent the responsibilities + duties I have as maintainer.

**Comment by rousskov** [comment]
> As I said on merge branching has happened.

You said that, but, for the purposes of this PR, branching had not happened. Yes, you created a branch named "v5". That 2019 action was premature and done without consensus, but, in itself, it did not cause any serious harm and does not constitute "official branching" for most practical purposes. I can create a branch named v7 right now, with the same (minimal) effect. (Official branches should not be created without consensus, of course, but I am focusing on a different violation here).

The real branching occurred when you merged this PR, committing first changes to v5. That happened on `Sat Jan 4 11:38:01 2020 +1300`, way _after_ my blocking comment. That unnecessary and harmful merge is exactly what my change request was blocking.

> Your blocker statement here was that is would not be needed before branching.

My statement was that this PR was not needed at all.

:exclamation: @yadij, please leave it to the reviewer to decide whether their change request has been addressed. Otherwise, a lot of reviews will be effectively ignored, and we will have nothing but chaos on our hands.

> All I see in regards to insults in PRs are ... or use of QA powers to prevent the responsibilities + duties I have as maintainer.

I do not have any such powers. Moreover, I generally stay away from your non-master maintenance activities. As I detailed above, this PR was effectively creating a _new_ branch. That important action is _not_ a maintainer prerogative (branch maintenance starts _after_ branching) -- it does require review, discussion, consensus, etc.

**Pull request merged**
