### PR TITLE
Bug 5055: FATAL FwdState::noteDestinationsEnd exception: opening

### PR DESCRIPTION
**Pull request by rousskov**
The bug was caused by commit 8eece63. Other known symptoms are:

    assertion failed: store.cc:1793: "isEmpty()"
    assertion failed: FwdState.cc:501: "serverConnection() == conn"
    assertion failed: FwdState.cc:1037: "!opening()"

This change has several overlapping parts. Unfortunately, merging
individual parts is both difficult and likely to cause crashes.

## Part 1: Bug 5055.

FwdState used to check serverConn to decide whether to open a connection
to forward the request. Since commit 8eece63, a nil serverConn pointer
no longer implies that a new connection should be opened: FwdState
helper jobs may already be working on preparing an existing open
connection (e.g., sending a CONNECT request or negotiating encryption).

Bad serverConn checks in both FwdState::noteDestination() and
FwdState::noteDestinationsEnd() methods led to extra connectStart()
calls creating two conflicting concurrent helper jobs.

To fix this, we replaced direct serverConn inspection with a
usingDestination() call which also checks whether we are waiting for a
helper job. Testing that fix exposed another set of bugs: The helper job
pointers or in-job connections were left stale/set after forwarding
failures. The changes described below addressed most of those problems.

## Part 2: Connection establishing helper jobs and their callbacks

A proper fix for Bug 5055 required answering a difficult question: When
should a dying job call its callbacks? We only found one answer which
required cooperation from the job creator and led to the following
rules:

* AsyncJob destructors must not call any callbacks.

* AsyncJob::swanSong() is responsible for async-calling any remaining
  (i.e. set, uncalled, and uncancelled) callbacks.

* AsyncJob::swanSong() is called (only) for started jobs.

* AsyncJob destructing sequence should validate that no callbacks remain
  uncalled for started jobs.

... where an AsyncJob x is considered "started" if AsyncJob::Start(x)
has returned without throwing.

A new JobWait class helps job creators follow these rules while keeping
track on in-progress helper jobs and killing no-longer-needed helpers.

Also fixed very similar bugs in tunnel.cc code.

## Part 3: ConnOpener fixes

1. Many ConnOpener users are written to keep a ConnectionPointer to the
   destination given to ConnOpener. This means that their connection
   magically opens when ConnOpener successfully connects, before
   ConnOpener has a chance to notify the user about the changes. Having
   multiple concurrent connection owners is always dangerous, and the
   user cannot even have a close handler registered for its now-open
   connection. When something happens to ConnOpener or its answer, the
   user job may be in trouble. Now, ConnOpener callers no longer pass
   Connection objects they own, cloning them as needed. That adjustment
   required adjustment 2:

2. Refactored ConnOpener users to stop assuming that the answer contains
   a pointer to their connection object. After adjustment 1 above, it
   does not. HappyConnOpener relied on that assumption quite a bit so we
   had to refactor to use two custom callback methods instead of one
   with a complicated if-statement distinguishing prime from spare
   attempts. This refactoring is an overall improvement because it
   simplifies the code. Other ConnOpener users just needed to remove a
   few no longer valid paranoid assertions/Musts.

3. ConnOpener users were forced to remember to close params.conn when
   processing negative answers. Some, naturally, forgot, triggering
   warnings about orphaned connections (e.g., Ident and TcpLogger).
   ConnOpener now closes its open connection before sending a negative
   answer.

4. ConnOpener would trigger orphan connection warnings if the job ended
   after opening the connection but without supplying the connection to
   the requestor (e.g., because the requestor has gone away). Now,
   ConnOpener explicitly closes its open connection if it has not been
   sent to the requestor.

Also fixed Comm::ConnOpener::cleanFd() debugging that was incorrectly
saying that the method closes the temporary descriptor.

Also fixed ConnOpener callback's syncWithComm(): The stale
CommConnectCbParams override was testing unused (i.e. always negative)
CommConnectCbParams::fd and was trying to cancel the callback that most
(possibly all) recipients rely on: ConnOpener users expect a negative
answer rather than no answer at all.

Also, after comparing the needs of two old/existing and a temporary
added ("clone everything") Connection cloning method callers, we decided
there is no need to maintain three different methods. All existing
callers should be fine with a single method because none of them suffers
from "extra" copying of members that others need. Right now, the new
cloneProfile() method copies everything except FD and a few
special-purpose members (with documented reasons for not copying).

Also added Comm::Connection::cloneDestinationDetails() debugging to
simplify tracking dependencies between half-baked Connection objects
carrying destination/flags/other metadata and open Connection objects
created by ConnOpener using that metadata (which are later delivered to
ConnOpener users and, in some cases, replace those half-baked
connections mentioned earlier. Long-term, we need to find a better way
to express these and other Connection states/stages than comments and
debugging messages.

## Part 4: Comm::Connection closure callbacks

We improved many closure callbacks to make sure (to the extent possible)
that Connection and other objects are in sync with Comm. There are lots
of small bugs, inconsistencies, and other problems in Connection closure
handlers. It is not clear whether any of those problems could result in
serious runtime errors or leaks. In theory, the rest of the code could
neutralize their negative side effects. However, even in that case, it
would only be a matter of time before the next bug bites us due to stale
Connection::fd and such. These changes themselves carry elevated risk,
but they get us closer to reliable code as far as Connection maintenance
is concerned. Without them, we will keep chasing deadly side effects of
poorly implemented closure callbacks.

Long-term, all these manual efforts to keep things in sync should become
unnecessary with the introduction of appropriate Connection ownership
APIs that automatically maintain the corresponding environments (TODO).

## Part 5: Other notable improvements in the adjusted code

Improved Security::PeerConnector::serverConn and
Http::Tunneler::connection management, especially when sending negative
answers. When sending a negative answer, we would set answer().conn to
an open connection, async-send that answer, and then hurry to close the
connection using our pointer to the shared Connection object. If
everything went according to the plan, the recipient would get a non-nil
but closed Connection object. Now, a negative answer simply means no
connection at all. Same for a tunneled answer.

Refactored ICAP connection-establishing code to to delay Connection
ownership until the ICAP connection is fully ready. This change
addresses primary Connection ownership concerns (as they apply to this
ICAP code) except orphaning of the temporary Connection object by helper
job start exceptions (now an explicit XXX). For example, the transaction
no longer shares a Connection object with ConnOpener and
IcapPeerConnector jobs.

Probably fixed a bug where PeerConnector::negotiate() assumed that
sslFinalized() does not return true after callBack(). It may (e.g., when
CertValidationHelper::Submit() throws). Same for
PeekingPeerConnector::checkForPeekAndSpliceMatched().
 
Fixed FwdState::advanceDestination() bug that did not save
ERR_GATEWAY_FAILURE details and "lost" the address of that failed
destination, making it unavailable to future retries (if any).

Polished PeerPoolMgr, Ident, and Gopher code to be able to fix similar
job callback and connection management issues.

Polished AsyncJob::Start() API. Start() used to return a job pointer,
but that was a bad idea:
    
* It implies that a failed Start() will return a nil pointer, and that
  the caller should check the result. Neither is true.

* It encourages callers to dereference the returned pointer to further
  adjust the job. That technically works (today) but violates the rules
  of communicating with an async job. The Start() method is the boundary
  after which the job is deemed asynchronous.
    
Also removed old "and wait for..." post-Start() comments because the
code itself became clear enough, and those comments were becoming
increasingly stale (because they duplicated the callback names above
them).

Fix Tunneler and PeerConnector handling of last-resort callback
requirements. Events like handleStopRequest() and callException() stop
the job but should not be reported as a BUG (e.g., it would be up to the
callException() to decide how to report the caught exception). There
might (or there will) be other, similar cases where the job is stopped
prematurely for some non-BUG reason beyond swanSong() knowledge. The
existence of non-bug cases does not mean there could be no bugs worth
reporting here, but until they can be identified more reliably than all
these benign/irrelevant cases, reporting no BUGs is a (much) lesser
evil.

TODO: Revise AsyncJob::doneAll(). Many of its overrides are written to
check for both positive (i.e. mission accomplished) and negative (i.e.
mission cancelled or cannot be accomplished) conditions, but the latter
is usually unnecessary, especially after we added handleStopRequest()
API to properly support external job cancellation events. Many doneAll()
overrides can probably be greatly simplified.

----

This is a manual backport of master/v6 commits 2b6b1bc and a8ac892.

### CODE REVIEW

**Comment by yadij** [comment]
Just to be clear. Does this backport contain the PR #939 fixup?

**Comment by rousskov** [comment]
> Does this backport contain the PR 939 fixup?

It does not. Do you want me to mangle the two backports together in this PR or wait until this PR lands? It is your call.

BTW, I described what this backport PR is backporting at the very bottom of the PR description, after the horizontal line. I think all backported PRs should have this kind of information, but, again, it is your call on whether to allow/adopt this. Please feel free to strip that info from the PR description, of course. I meant to mention this earlier but forgot.

**Comment by yadij** [comment]
> > Does this backport contain the PR 939 fixup?
> 
> It does not. Do you want me to mangle the two backports together in this PR or wait until this PR lands? It is your call.
> 

Since it is a fix of the code being backported here,  yes please include it like the 3d9b009 fixup was.

> BTW, I described what this backport PR is backporting at the very bottom of the PR description, after the horizontal line. I think all backported PRs should have this kind of information, but, again, it is your call on whether to allow/adopt this. Please feel free to strip that info from the PR description, of course. I meant to mention this earlier but forgot.

Thanks for that. It does help my manual processes. I will have to give some thought to how the automation can use it.

**Comment by rousskov** [comment]
> Since it is a fix of the code being backported here, yes please include it 

Done: Commit f5cdf27. I have also updated the PR description footer accordingly.

> like the [3d9b009](https://github.com/squid-cache/squid/commit/3d9b009adf865bb21f52395a895e2bb22e2714a9) fixup was.

Not sure what you mean because PR branch commit 3d9b009 did not include any official commits while PR branch commit f5cdf27 is a backport of an official commit. If you want to squash or edit any branch commits, please feel free to do that!

> I will have to give some thought to how the automation can use it.

This information is meant primarily for human use and is often too varied/nuanced to be correctly interpreted by automation in general. However, automation can (and, IMO, should) add similar footers to fully automated packporting commits. In theory, those automated footers can also be recognized/used by automation.

**Comment by rousskov** [comment]
I have removed the Draft flag and do not plan on doing further testing. During the tests, I did not notice any new problems. I do not have access to busy production deployments willing to run this code, but the code this (large/complex) fix is _based_ on runs in several production environments. This is probably the best we can do for now in terms of testing.

When testing, I did hit bug [5090](https://bugs.squid-cache.org/show_bug.cgi?id=5090) (fixed in master/v6 PR #930), but that is a separate bug. The master/v6 fix (commit 15bde30) applies cleanly to this PR branch so it should be easy to backport once this lands. The only wrinkle with #930 is that we should do a followup [polishing](https://github.com/squid-cache/squid/pull/930#discussion_r747885532) PR. Ideally, the _combined_ changes should be ported to v5 to avoid introducing unnecessary differences in this sensitive and complicated code (IMO).

**Comment by yadij** [comment]
@rousskov for some reason github is not offering me the controls to update and merge this. Can you please see if you can do it?

**Comment by rousskov** [comment]
> github is not offering me the controls to update and merge this

I was able to update the branch by clicking on the usual GitHub "Update branch" button. I do not know why it was not available to you; did you try to reload this GitHub page?

The PR is waiting for the new CI results now. Please note that the previous CI tests for the staging commit [b09f925](https://github.com/squid-cache/squid/commit/b09f92532370b6b8b9816b328b4b3376c6719eb5) have [failed](https://build.squid-cache.org/job/5-pr-auto/COMPILER=clang,OS=centos-8,label=docker-build-host/1042/console) on Jenkins. On Zulip, I pinged @kinkie about similar Jenkins `Unknown test specs '--progress'` failures on February 4, 2022.

This is a v5 PR, and I do not know what your usual approach to staging failures for v5 PRs is. Do you want me to eventually merge this PR despite staging failures (if they resurface for the new staging commit)?

**Comment by yadij** [comment]
Thank you, that worked. yes I reloaded a few times, not sure what was going on.

FTR; the only things I ignore are Anubis-specific errors and lack of votes-for. All other issues or hiccups block that merge until fixed.

**Comment by rousskov** [comment]
> All other issues or hiccups block that merge until fixed.

FWIW, all Jenkins tests have failed for the staged commit 16bac1d. Look above for :x: mark next to that commit SHA.

And the (rather garbled) merged commit message (1332f8d) is different from that staged commit message (and the PR description).

If this is all known/intentional, please disregard my comment. Otherwise, please let me know if I can help avoid similar problems in the future.

**Pull request merged**
