### PR TITLE
Fix doc/debug-messages.dox generation

### PR DESCRIPTION
**Pull request by eduard-bagdasaryan**
cache_log_message ID 62 was missing from doc/debug-messages.dox because
the code generating that file did not recognize debugs() statements with
Critical() or Important() macro inside a conditional operator.

Also fixed a related sed regex: sed does not support non-greedy matches.

No runtime functionality changes.

### CODE REVIEW

**Review by rousskov — COMMENTED** [review]
I do not know why this PR triggered it, but please see if you can triage this Semaphore CI [rejection](https://semaphoreci.com/squid/squid/branches/pull-request-871/builds/1):

```
running: ./scripts/source-maintenance.sh --check-and-update-copyright no
...
ERROR: Repeated debugs() message gists:
FD ...
```

**Comment by eduard-bagdasaryan** [comment]
There was a problem in a sed regular expression, which [does not support](https://stackoverflow.com/questions/1103149/non-greedy-reluctant-regex-matching-in-sed) non-greedy quantifiers.

**Review by rousskov — APPROVED** [review]
Thank you for fixing these two bugs. Please double check that the polished PR title/description are still acceptable.

**Review by yadij — APPROVED** [review]
LGTM

**Comment by eduard-bagdasaryan** [comment]
> polished PR title/description

Fine by me.

**Pull request closed without merging**
