### PR TITLE
negotiate_kerberos_auth: Do not prohibit all LDFLAGS

### PR DESCRIPTION
**Pull request by yadij**

### CODE REVIEW

**Review by kinkie — APPROVED** [review]

**Review by rousskov — COMMENTED** [review]
Should this PR fix ext_kerberos_ldap_group_acl_LDFLAGS as well?

**Comment by yadij** [comment]
> ext_kerberos_ldap_group_acl_LDFLAGS

That is a different helper, different change. Will do as a followup.

**Review by rousskov — APPROVED** [review]
FWIW, another red flag is that we sometimes add LIBADD_DL to program-specific LDFLAGS and sometimes do not [have program-specific LDFLAGS].

**Comment by squidadm** [comment]
queued for backport to v6

**Pull request closed without merging**
