### PR TITLE
ext_lm_group_acl: Improved username handling

### PR DESCRIPTION
**Pull request by aaron-costello**

### CODE REVIEW

**Comment by aaron-costello** [comment]
Once I have time (coming days, week), I'll make a move on replacing the use of strcpy in src/acl/external/* in one large PR.

**Comment by rousskov** [comment]
OK to test

**Comment by rousskov** [comment]
> If that commit works for you, I will clear this PR for merging.

Waiting for @aaron-costello confirmation.

**Comment by aaron-costello** [comment]
@rousskov Can confirm this is fine on my side, thank you.

**Pull request closed without merging**
