### PR TITLE
Maintenance: update --with-heimdal-krb5 detection

### PR DESCRIPTION
**Pull request by yadij**

### CODE REVIEW

**Comment by kinkie** [comment]
Looks good, but one question: if both gnugss and heimdal are present, which one should we favour and why?

**Comment by yadij** [comment]
The existing code prefers MIT, Heimdal, GSS in that order. At present I am not changing that due to lack of understanding the specific reasons for preferences.

AFAIK some OS (re-)implementations of libgss lack a fully functional Kerberos or GSSAPI feature set. But it is still the most widely available by default in Linux and BSD distributions. So worth checking for.

**Review by kinkie — APPROVED** [review]
Thanks

**Review by rousskov — COMMENTED** [review]
I am unable to efficiently review most of the changes in this PR.

**Pull request closed without merging**
