### PR TITLE
Fix cross-compile detecting kerberos due to AC_RUN_IFELSE

### PR DESCRIPTION
**Pull request by yadij**
Authored-by: Helmut Grohne <helmut@subdivi.de>

### CODE REVIEW

**Review by kinkie — COMMENTED** [review]
Do you mind showing a snippet of configure output before and after the change?
Thanks

**Comment by yadij** [comment]
This is from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1063877.
The OS I cross-build for do not have Heimdal packages available for me to replicate the `./configure` output.

**Comment by kinkie** [comment]
Good for me. Sourceformat needs to be run, apparently

**Review by kinkie — APPROVED** [review]

**Review by rousskov — APPROVED** [review]
Thank you for posting this fix.

I assume you want this fix to be merged with Helmut as the author. I have added Helmut to the PR description so that Anubis uses that [custom author](https://github.com/measurement-factory/anubis/blob/master/README.md#pr-description) (instead of the PR author default) for the staged commit when the time comes to stage and merge this PR changes. Please adjust as needed.

CONTRIBUTORS update is needed to pass [CI source-maintenance tests](https://github.com/squid-cache/squid/actions/runs/9687382799/job/26731896226?pr=1851), of course.

P.S. It would be good to apply the same kind of fixes to other AC_RUN() use cases that do not need to run the test program (e.g., SQUID_USE_SSLGETCERTIFICATE_HACK) but that work can be reasonably viewed as out of scope. I am _not_ requesting (or even recommending) it for this PR.

**Review by rousskov — APPROVED** [review]

**Review by kinkie — APPROVED** [review]

**Review by rousskov — COMMENTED** [review]
> PR description: Reference point for automated CONTRIBUTORS updates

@yadij, do we have to add that key phrase to merge this PR? If not, please remove it. That key phrase is not meant to be used with ordinary CONTRIBUTORS updates like the one being done in this PR. Its primary goal is to _overwrite_ automated updates. It is similar to a `--force` command line parameter in various tools. I hope that such an overwrite/force is not necessary here (and, hence, should not be used).

**Comment by rousskov** [comment]
> > > PR description: Reference point for automated CONTRIBUTORS updates

> > @yadij, do we have to add that key phrase to merge this PR? If not, please remove it. That key phrase is not meant to be used with ordinary CONTRIBUTORS updates like the one being done in this PR. Its primary goal is to _overwrite_ automated updates. It is similar to a `--force` command line parameter in various tools. I hope that such an overwrite/force is not necessary here (and, hence, should not be used).
 
> Oh, I was of the understanding this was a reference point to stop the automation checking for older changes. 

It is. My point is that we should not add these forced stops where they are not necessary to pass automation checks. Thank you for removing that key phrase.

> Since I ran the automation manually and verified the `CONTRIBUTORS` update for this PR is correct for every existing change to now it seemed appropriate to add it here and speed up future automation checks.

I hesitate going as far as calling that addition inappropriate, but it is not wanted: Its speed optimization side effect is too small to matter. The negative effects of disabling automated checks (e.g., risks, noise, and bad examples) outweigh that non-measurable optimization benefit. Let's only add it when we have to.

**Comment by yadij** [comment]
Scheduled for backport in PR #1866

**Pull request closed without merging**
