### PR TITLE
Deduplicate transaction LogTags

### PR DESCRIPTION
**Pull request by eduard-bagdasaryan**
...using ALE cache.code instead of its partial
ClientSideRequest::logType duplicate.

The need to de-duplicate these two LogTag members became apparent when
we tried to update/detail LogTags in forwarding code (e.g., to report
peer timeouts) and noticed that ALE cache.code value could be
overwritten by (stale) ClientSideRequest::logType information. Those
updates needed other significant changes, so we factored this small
stand-alone improvement out.

Fortunately, ClientSideRequest::logType lifetime does not exceed ALE's,
making ClientHttpRequest::logTags removal straightforward.

Also removed a paranoid TunnelStateData::al check after verifying that
the ALE pointer is never nil.

### CODE REVIEW

**Review by yadij — APPROVED** [review]

**Comment by yadij** [comment]
@eduard, Just needs this new conflict resolved and it can be cleared for merge again.

**Comment by rousskov** [comment]
> Just needs this new conflict resolved and it can be cleared for merge again.

FYI: We do not need to remove merge clearance just because there are merge conflicts. Anubis should not merge conflicting (from git point of view) PRs.

**Comment by yadij** [comment]
> > Just needs this new conflict resolved and it can be cleared for merge again.
> 
> FYI: We do not need to remove merge clearance just because there are merge conflicts. Anubis should not merge conflicting (from git point of view) PRs.

Have you fixed the bug where Anubis will stop at the first M-cleared-for-merge PR with conflicts until it is fixed and not attend to any others?

**Comment by rousskov** [comment]
> Have you fixed the bug where Anubis will stop at the first M-cleared-for-merge PR with conflicts until it is fixed and not attend to any others?

Sorry, I do not recall that specific bug, and my quick search through Anubis commits and open projects did not result in any clear matches. Perhaps @eduard-bagdasaryan knows the answer. If not, a reference to the corresponding discussion somewhere may help us answer your question (and re-prioritize the fix if it is needed).

**Comment by eduard-bagdasaryan** [comment]
> Have you fixed the bug where Anubis will stop at the first M-cleared-for-merge PR with conflicts

I could not recall such bug. Normally, Anubis should put such a conflicted PR aside and take another one. Please let me know if you notice that Anubis gets stuck in this situation.

**Pull request closed without merging**
