### PR TITLE
Allocate fast-checking ACLFilledChecklists on stack

### PR DESCRIPTION
**Pull request by eduard-bagdasaryan**
There is no need for dynamic allocation risks and performance overheads
in these simple "immediate fastCheck()" cases.

This change converts all dynamically allocated checklists that use only
fastCheck() calls except one: Security::PeerConnector::initialize() has
to allocate its checklist dynamically to pass it to SSL_set_ex_data().

### CODE REVIEW

**Review by rousskov — APPROVED** [review]

**Comment by eduard-bagdasaryan** [comment]
retest this please

**Comment by eduard-bagdasaryan** [comment]
@kinkie , it looks like that our Jenkins scripts cannot start building this PR:

```
14:14:38 [workspace] $ /bin/sh -xe /tmp/jenkins7102295577578922598.sh
14:14:38 FATAL: command execution failed
14:14:38 java.io.IOException: error=0, Failed to exec spawn helper: pid: 4067515, exit value: 1
```

**Comment by kinkie** [comment]
> @kinkie , it looks like that our Jenkins scripts cannot start building this PR:
> 
> ```
> 14:14:38 [workspace] $ /bin/sh -xe /tmp/jenkins7102295577578922598.sh
> 14:14:38 FATAL: command execution failed
> 14:14:38 java.io.IOException: error=0, Failed to exec spawn helper: pid: 4067515, exit value: 1
> ```

We had a similar issue yesterday; I had checked on the workers but couldn't see any obvious issue.
I've upgraded Jenkins to see if we had fallen victim to a bug

**Comment by kinkie** [comment]
Ok to test

**Review by yadij — APPROVED** [review]

**Comment by kinkie** [comment]
What about using an std::unique_ptr here instead? It would retain the same benefits in scope management, but without allocating things on the stack

**Review by kinkie — CHANGES_REQUESTED** [review]
What about using an std::unique_ptr here instead? It would retain the same benefits in scope management, but without allocating things on the stack

**Comment by eduard-bagdasaryan** [comment]
> What about using an std::unique_ptr here instead

I do not see any benefit in creating an unique_ptr<A> if we can simply create A. Moreover, unique_ptr will allocate on heap, and that is what we are trying to optimize here.

**Review by kinkie — APPROVED** [review]
Ok, if it's delberate, let's proceed

**Pull request closed without merging**
