### PR TITLE
Source Format Enforcement

### PR DESCRIPTION
**Pull request by squidadm**
.

### CODE REVIEW

**Comment by yadij** [comment]
OK to test

**Comment by yadij** [comment]
@eduard-bagdasaryan , @rousskov - can you please look into why Anubis has not merged this already. It should have merged several days ago when everything was green and the audit build completed. The recent semaphore fail only happened after rebuild was kicked (if there is a way to get that check to re-run please initiate it).

**Comment by eduard-bagdasaryan** [comment]
> why Anubis has not merged

This happened because Jenkins staged [tests](https://build.squid-cache.org/job/5-pr-auto/567) finished _after_ the Semaphore [failure](https://semaphoreci.com/squid/squid/branches/pull-request-579/builds/2).
Before performing the final merge (after staging tests completion), Anubis verifies again that all other checks are still ok. If something is broken (our case), it schedules the PR from scratch.

**Comment by rousskov** [comment]
FTR, I changed the Semaphore script in hope to avoid similar intermittent [failures](https://semaphoreci.com/squid/squid/branches/pull-request-579/builds/2).

**Pull request closed without merging**
