### PR TITLE
Unit empty string == bytes

### PR DESCRIPTION
**Pull request by mahdi1001**
Add empty string check for byte unit.

### CODE REVIEW

**Comment by yadij** [comment]
parseBytesUnits() should only ever be called with a unit string. So this looks like a wrong fix to the recently uncovered problems with config parsing of units.

Since we have a mixed situation of config setting having optional vs mandatory vs no units, and differing placement regards to whitespaces the function calling parseBytesUnits() should detect where the units come from.

IMHO, we should probably add generic support for bytes parameters using the string "none" as 0. This will need some planning discussion in squid-dev mailing list though to get buy-in from the other devs since "none" is already special cased in many directives with value -1.

**Comment by rousskov** [comment]
> we should probably add generic support for bytes parameters using the string "none" as 0

FWIW, I do not understand what `generic support for bytes parameters using the string "none" as 0` means. The only interpretation I can imagine here is that admins would be able to write `foo=none` instead of `foo=0` (or equivalent) but that does not really make sense -- `none` is clearly worse than `0` in this context -- so you probably meant something else.

**Comment by mahdi1001** [comment]
For example :
Buffer-size=256  is invalid. You should entered "Buffer-size=256byte" completly.
I just fixed this problem.

**Comment by rousskov** [comment]
> Buffer-size=256 is invalid.

And, IMO, should stay invalid. Squid may need better error reporting, but it is best to require explicit units for non-zero size values where possible. It is not difficult to type "bytes", and there have been costly configuration bugs where admins assumed a wrong default size unit for some of the configuration options.

**Comment by yadij** [comment]
By the "none" support I mean adjusting the parse_access_log function to special case "buffer-size=none" to set the cl->bufferSize=0 akin to turning "buffered_logs off" for just this one output. Having a bufferSize of 0 is already special-cased in the UDP writeline() logic to skip buffer use.

**Comment by rousskov** [comment]
IMO `none` is clearly worse than `0` in this context -- I see no advantages in adding support for `none` sizes where we can support `0` sizes.

**Pull request closed without merging**
