### PR TITLE
V4 next backports

### PR DESCRIPTION
**Pull request by squidadm**

### CODE REVIEW

**Comment by yadij** [comment]
OK to test

**Comment by rousskov** [comment]
To avoid misunderstanding: I am blocking this PR to get your attention because [it](https://github.com/squid-cache/squid/pull/648#pullrequestreview-421197410) is a serious issue, and you have not responded to my previous comment about it. I will unblock once you acknowledge that you are aware of the problem, even if you disagree that the problem deserves the fix in this PR.

**Comment by yadij** [comment]
Thank you. Reverting in this update. Though note the commit messages from the v5 PR explicitly state "These loops do not have ABA update problems".

**Comment by rousskov** [comment]
> Though note the commit messages from the v5 PR explicitly state "These loops do not have ABA update problems".

Yes, I know. This bug was disclosed on squid-bugs in my email dated 2020-03-07.

**Pull request merged**
