### PR TITLE
Bug 4847 pt1: regression in proxy_auth ACL flags

### PR DESCRIPTION
**Pull request by yadij**
r15058 "Support for --long-acl-options" in Squid-4.0.21
unintentionally removed the proxy_auth ACL support for -i/+i
flags. See bug report for details.

Fix proxy_auth ACL -i and +i flags no longer working by copying
RegexData flags registration, since ACLs for UserData all use
the same names and meanings.

Add documentation to indicate that ident and ext_user ACLs do
support -i/+i just like proxy_auth ACLs.

TODO: fix server_cert_fingerprint ACL which is still broken.

### CODE REVIEW

**Comment by rousskov** [comment]
If `ident` and `ext_user` ACLs are also affected, then I recommend replacing the current (difficult to parse) PR description with a list of the affected ACLs and a brief mentioning of the bug symptoms.

**Comment by yadij** [comment]
Using s/theFlagNames/flags/ produces compile errors because "flags" is being used elsewhere in the same class.

Good point on ident and ext_user, they have never been documented as having -i/+i support but do anyway. Adding that documentation now.

**Comment by rousskov** [comment]
bq. Using s/theFlagNames/flags/ produces compile errors because "flags" is being used elsewhere in the same class.

It looks like I forgot to add "(or similar)" to my renaming suggestion. Sorry. I am sure you can find a good name that does not suffer from either of the two problems.

**Comment by yadij** [comment]
Perhapse you could explain why use of "the" to name a variable is such a "problem" (and thus a bad idea) when the code most populated with theFoo for variable names is found to be Factory patches? (src/adaptation/, src/ipc/, etc)

**Comment by rousskov** [comment]
As I have already explained, the small `the` prefix is for data members in legacy code (and equivalent). Using that prefix for non-members confuses the reader who is familiar with that convention (the convention itself is not limited to Squid and did not originate in Squid). This general principle host regardless of who violates it.

If a Factory pull request uses that prefix for something else, then that pull request is as wrong as yours and should be fixed (of course).

**Comment by yadij** [comment]
The prefix for members is very rarely used in legacy code. It is most frequent being added in fairly recent code and classes coming out of Factory: Notes, Adaptation, SMP classes. Usually for function and method variables, very rarely members. I suspect the legacy code prior to my time which uses it as well has similar origins.

If its going to be held up as a *problem* can we get a good reference describing what the convention is? and added to the coding style guidelines so I can point at that next time you reject a cleanup patch/PR removing 'the' prefixes. Right now its just you like it one way, I like other code that self-documents:
   return theFlagNames; // return the flag names
vs
  return flagNames; // (all or some? are there more? where do I find those others?)

**Comment by rousskov** [comment]
> I'm seeking more to understand the why behind that change away from it

I assume "it" means "using `the` prefix for data members". The wiki page commit message answers the your "why" question:

> Wiki: A name should use either underscore suffix or "the" prefix, not both! For consistency, we should standardize on one approach and underscore wins, on most levels.

> Amos: is there actually a convention for use or non-use of 'the'

I believe I have already stated that there is.

> I've never heard of one and am interested in why it would be so.

I do not know why you have not heard of it, but it is possible that you have not studied naming issues enough to discover some of the less-popular alternatives.

FWIW, I do not know (or remember) where the idea of using `the` prefix for C++ names originated from. I am sure that it was born more than 17 years ago and outside of Squid. I probably brought it into Squid 17+ years ago and applied it to data members. Other ideas won, but folks still mention and even advocate that old `the` prefix idea [around](https://stackoverflow.com/a/1228868) [the](https://blogs.msdn.microsoft.com/ericgu/2007/06/15/to-m_-or-no-to-m_-that-is-the-question/#comment-71463) [web](https://code.i-harness.com/en/q/8644a).

> The justification for such changes is that of technical debt overheads

Leaving poorly styled code as is until it needs to be changed for other reasons is often the overall best approach. Squid Project inability to use this approach is as amazing as it is unfortunate. IMO, there is absolutely no need to waste so much time on these issues, but I do not know how to stop folks from creating that waste. Most of the costs you attribute to "technical debt" are actually non-technical self-inflicted wounds! I really doubt that any bulk style-only code changes would be enough to end that pain and suffering.

Technical debt does not necessarily outweigh the overheads created by the changes and, even when it does, there may be far more important/valuable changes that should be done instead. There is no single rule that works well for all bulk editing cases -- each case has to be judged on its individual merits. I can only hope that you are not going to start removing wrong `the`s from the otherwise unchanged committed code.

**Comment by yadij** [comment]
Something has gone wrong. Anubis squashed these PR 191 changes into the commit for PR 189.
Both were ready for merge so its not breaking anything else, but still should not have happened.

**Comment by rousskov** [comment]
> Something has gone wrong

@eduard-bagdasaryan, please investigate. I killed the bot to avoid additional damage.

**Comment by eduard-bagdasaryan** [comment]
I don't think the bot 'squashed' something wrong. I assume the conflict we see is due to a change independently added into two branches: this yadij:bug4847 (486e981d64f32009f03fa3483d52a4242ea99fb9) and PR189 yadij:v5-acl-docs (0c3fc73c89f99ce8e36eb3b56bcde7e4a97a5980).

**Comment by rousskov** [comment]
> I assume the conflict we see is due to a change independently added into two branches

Yes, but Amos says that he did not add that change to one of those two branches. Can we somehow confirm that the bot did not do it? I know that the Committer field does not point to Anubis, but I do not know whether that is enough to clear Anubis from any suspicions.

**Comment by eduard-bagdasaryan** [comment]
> but I do not know whether that is enough to clear Anubis from any suspicions.

I can assure that the bot does not create any commits for PR branches. If we look at this from the paranoid point of view (i.e., suspect that the bot got off the rails somehow), then this (wrong) activity should be accompanied by some label creation (e.g., M-waiting-staging-checks), which did not happen.

**Comment by rousskov** [comment]
@eduard-bagdasaryan, does GitHub record a history of push events for a repository? If yes, can that history be used to identify who pushed the wrong commits?

**Comment by eduard-bagdasaryan** [comment]
> does GitHub record a history of push events for a repository

This event list can be found in webhooks event history. There should be several hooks configured for Squid. We need a one with 'push' event configured (e.g., the one configured for Jenkins auto-branch needs). In this event details, "pusher" field should contain the required information.

**Comment by eduard-bagdasaryan** [comment]
To avoid future debates, I have used an GitHub API [call](https://developer.github.com/v3/activity/events/#list-events-performed-by-a-user) to get required push events and found the one we need:

```
{
    "id": "7567555435",
    "type": "PushEvent",
    "actor": {
      "id": 9123754,
      "login": "yadij",
      "display_login": "yadij",
      "gravatar_id": "",
      "url": "https://api.github.com/users/yadij",
      "avatar_url": "https://avatars.githubusercontent.com/u/9123754?"
    },
    "repo": {
      "id": 97826891,
      "name": "yadij/squid",
      "url": "https://api.github.com/repos/yadij/squid"
    },
    "payload": {
      "push_id": 2505562915,
      "size": 3,
      "distinct_size": 3,
      "ref": "refs/heads/v5-acl-docs",
      "head": "0c3fc73c89f99ce8e36eb3b56bcde7e4a97a5980",
      "before": "b003ced70fa5307142a54189bf12c66884d6e049",
      "commits": [
        {
          "sha": "feebabcfef6cc418bb914fabcfa4f08594b1c95f",
          "author": {
            "email": "amosjeffries@squid-cache.org",
            "name": "Amos Jeffries"
          },
          "message": "Add regression testing config file",
          "distinct": true,
          "url": "https://api.github.com/repos/yadij/squid/commits/feebabcfef6cc418bb914fabcfa4f08594b1c95f"
        },
        {
          "sha": "b5528396e15ddfb28b67e85b23a38e0ae22821d4",
          "author": {
            "email": "amosjeffries@squid-cache.org",
            "name": "Amos Jeffries"
          },
          "message": "Fix test cases to avoid wrong reason for proxy_auth failures",
          "distinct": true,
          "url": "https://api.github.com/repos/yadij/squid/commits/b5528396e15ddfb28b67e85b23a38e0ae22821d4"
        },
        {
          "sha": "0c3fc73c89f99ce8e36eb3b56bcde7e4a97a5980",
          "author": {
            "email": "amosjeffries@squid-cache.org",
            "name": "Amos Jeffries"
          },
          "message": "Fix proxy_auth -i/+i flags\n\nCopy RegexData flags registration, since ACLs for UserData uses\nthe same names and meanings.",
          "distinct": true,
          "url": "https://api.github.com/repos/yadij/squid/commits/0c3fc73c89f99ce8e36eb3b56bcde7e4a97a5980"
        }
      ]
    },
    "public": true,
    "created_at": "2018-04-22T11:21:29Z"
  }
```

As you can see, the 'actor' is not 'squid-anubis'.

**Comment by yadij** [comment]
The actor for that repository should always be me since it is my private one and I am the only user with rights to push things to it - that seems normal. What is abnormal is the commit hashes and branch not lining up.

I went to compare the timestamp against the actual commits this PR has and no sign of the 486e981d64f32009f03fa3483d52a4242ea99fb9 commit being pushed, which the bots ran tests on and Alex reviewed - just this 0c3fc73c89f99ce8e36eb3b56bcde7e4a97a5980 thing. Something very weird is going on.

**Comment by yadij** [comment]
removing the merge label until master branch is back to non-conflicting state (PR 199 gets merged)

**Comment by rousskov** [comment]
> The actor for that repository should always be me since it is my private one and I am the only user with rights to push things to it

Are you sure you do not allow others to push into your PR branches? IIRC, allowing such pushes is the _default_ for GitHub PRs. I cannot check whether yadij:v5-acl-docs branch was editable by others, but it looks like I can edit the files on your yadij:bug4847 branch right now (for example). I do not know whether Anubis bot can push into your branches (not every GitHub user can, of course), but I would not be surprised if it has enough rights to do so.

And, perhaps more importantly, we are investigating an event that should not happen. Thus, we cannot assume that _everything_ that should be true actually is. We should double check what we can. The information found by Eduard is valuable because it answers some (but not all) of the questions we have (assuming GitHub history itself is not lying).

> no sign of the 486e981 commit being pushed

That question remains open. I hope @eduard-bagdasaryan can answer it by looking further into the branch push history on GitHub.

If you still have shell history from the push around `2018-04-22T11:21:29Z`, it may explain how that particular push happened (and partially validate GitHub history).

**Comment by eduard-bagdasaryan** [comment]
> I went to compare the timestamp against the actual commits this PR has and no sign of the 486e981 commit being pushed, which the bots ran tests on and Alex reviewed - just this 0c3fc73 thing. Something very weird is going on.

I made an experiment which showed that GitHub creates just "PullRequestEvent" if we create both PR branch and the PR itself. This is possible if check "Create a new branch for this commit and start a pull request" on GitHub while editing a file online directly. So, for the first PR commit (as 486e981 is), we would not see "PushEvent" in this case.

I am going to post GitHub API results for both PR189 and PR191 below.

**Comment by rousskov** [comment]
> removing the merge label until master branch is back to non-conflicting state

FYI: Anubis will not merge conflicting PRs, even if they are cleared for merging by a human. The label is necessary (for now) but not sufficient merge precondition. Thus, it is technically safe label a currently conflicting PR.

**Comment by eduard-bagdasaryan** [comment]
Here is the events history for this PR191. For convenience, I removed some (unimportant) fields from the API output. The 'mysterious' 486e981 goes the first.

```
  {
    "id": "7567910709",
    "type": "PullRequestEvent",
    "actor": {
      "login": "yadij",
    },
    "payload": {
      "action": "opened",
      "title": "Bug 4847: regression in proxy_auth ACL flags",
    }
    "created_at": "2018-04-22T14:59:49Z",
    "updated_at": "2018-04-22T14:59:49Z",
    "head": {
       "label": "yadij:bug4847",
       "ref": "bug4847",
       "sha": "486e981d64f32009f03fa3483d52a4242ea99fb9",
    }
  }

  {
    "id": "7570345544",
    "type": "PushEvent",
    "actor": {
      "login": "yadij",
    },
    "repo": {
      "name": "yadij/squid",
    },
    "payload": {
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/bug4847",
      "head": "7053934e5fce4a09442ab2eb183cab8a23134858",
      "before": "486e981d64f32009f03fa3483d52a4242ea99fb9",
      "commits": [
        {
          "sha": "7053934e5fce4a09442ab2eb183cab8a23134858",
          "author": {
            "email": "amosjeffries@squid-cache.org",
            "name": "Amos Jeffries"
          },
          "message": "Document -i/+i flags for ident and ext_user ACLs",
        }
      ]
    },
    "created_at": "2018-04-23T08:43:16Z"
  },

  {
    "id": "7573436948",
    "type": "PushEvent",
    "actor": {
      "login": "yadij",
    },
    "repo": {
      "name": "yadij/squid",
    },
    "payload": {
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/bug4847",
      "head": "f85bb84e131e694e8d1dd8a36603838474fd31b2",
      "before": "7053934e5fce4a09442ab2eb183cab8a23134858",
      "commits": [
        {
          "sha": "f85bb84e131e694e8d1dd8a36603838474fd31b2",
          "author": {
            "email": "amosjeffries@squid-cache.org",
            "name": "Amos Jeffries"
          },
          "message": "Remove 'the' definitive\n\nBy Alex request, despite this being a definitive state.\n\n'flags' conflicts with ACLUserData::flags member used to\nstore the flag values in more conventional use of the\nmember name 'flags' for flag structures.",
          "distinct": true,
          "url": "https://api.github.com/repos/yadij/squid/commits/f85bb84e131e694e8d1dd8a36603838474fd31b2"
        }
      ]
    },
    "created_at": "2018-04-23T17:46:23Z"
  },

```

**Comment by eduard-bagdasaryan** [comment]
And here are first three events for three first revisions of the merged PR189. The last three revisions were single-pushed as I noted [above](https://github.com/squid-cache/squid/pull/191#issuecomment-386230906).

```
  {
    "id": "7565541418",
    "type": "PullRequestEvent",
    "actor": {
      "login": "yadij",
    },
    "payload": {
      "action": "opened",
      "title": "Documentation for several ACL types",
    }
    "created_at": "2018-04-21T11:11:58Z",
    "updated_at": "2018-04-21T11:11:58Z",
    "head": {
      "label": "yadij:v5-acl-docs",
      "ref": "v5-acl-docs",
      "sha": "6145a8e4ce7358f41a1cb7beaf445fda2a74de8b",
     }
  }

  {
    "id": "7565550786",
    "type": "PushEvent",
    "actor": {
      "login": "yadij",
    },
    "repo": {
      "name": "yadij/squid",
    },
    "payload": {
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/v5-acl-docs",
      "head": "a9e77854082c06ba24fc37dedd6c58b90a6e6702",
      "before": "6145a8e4ce7358f41a1cb7beaf445fda2a74de8b",
      "commits": [
        {
          "sha": "a9e77854082c06ba24fc37dedd6c58b90a6e6702",
          "author": {
            "email": "amosjeffries@squid-cache.org",
            "name": "Amos Jeffries"
          },
          "message": "Fix typo in squid.conf parser debug message",
          "distinct": true,
          "url": "https://api.github.com/repos/yadij/squid/commits/a9e77854082c06ba24fc37dedd6c58b90a6e6702"
        }
      ]
    },
    "created_at": "2018-04-21T11:19:00Z"
  },

  {
    "id": "7566547370",
    "type": "PushEvent",
    "actor": {
      "login": "yadij",
    },
    "repo": {
      "name": "yadij/squid",
    },
    "payload": {
      "push_id": 2504883057,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/v5-acl-docs",
      "head": "b003ced70fa5307142a54189bf12c66884d6e049",
      "before": "a9e77854082c06ba24fc37dedd6c58b90a6e6702",
      "commits": [
        {
          "sha": "b003ced70fa5307142a54189bf12c66884d6e049",
          "author": {
            "email": "amosjeffries@squid-cache.org",
            "name": "Amos Jeffries"
          },
          "message": "MAC and EUI ACLs only work if --enable-eui and eui_lookup on",
          "distinct": true,
          "url": "https://api.github.com/repos/yadij/squid/commits/b003ced70fa5307142a54189bf12c66884d6e049"
        }
      ]
    },
    "created_at": "2018-04-21T21:45:12Z"
  },
```

**Comment by eduard-bagdasaryan** [comment]
So the final conclusion: GitHub history for PR189 and PR191 looks clear, no bot activity was noticied. @yadij, do you have any more questions about this?

**Comment by rousskov** [comment]
One thing we have learned is that GitHub PR pages, when rendering events, use commit author dates instead of commit push dates, which may "move" a commit earlier in the rendered history, placing it _before_ the events that happened _after_ that commit. This can be very confusing to humans!

Here is the human-friendlier version of what actually happened, based on the combination of GitHub history provided by Eduard and GitHub history from the PR web page. Note the **XXX**s in the middle.

```
2018-04-21T11:10:29Z Amos creates commit 6145a8e
2018-04-21T11:11:58Z Amos creates PR with 6145a8e

+7 minutes

2018-04-21T11:18:45Z Amos creates commit a9e7785
2018-04-21T11:19:00Z Amos pushes commit a9e7785

+10 hours

2018-04-21T15:12:21Z Alex approves PR

+6 hours

2018-04-21T21:44:44Z Amos creates commit b003ced
2018-04-21T21:45:12Z Amos pushes commit b003ced

+5 hours

2018-04-22T02:47:22Z Amos labels PR with M-cleared-for-merge

+9 hours

2018-04-21T23:55:06Z Amos creates commit feebabc
XXX: There is no push event dedicated to this commit. 
Thus, GitHub does not know about it, and CI does not test it.

+11 hours

2018-04-22T11:18:38Z Amos creates commit b552839
XXX: There is no push event dedicated to this commit. 
Thus, GitHub does not know about it, and CI does not test it.

+ 3 hours

2018-04-22T11:21:02Z Amos creates commit 0c3fc73
2018-04-22T11:21:29Z Amos pushes three commits: feebabc b552839 0c3fc73

+8 days

2018-04-30T22:14:22Z Anubis stages PR (as of 0c3fc73) for testing

+3 hours

2018-05-01T01:20:15Z Anubis merges PR (as of 0c3fc73)
```

**Comment by rousskov** [comment]
We still do not know exact where the three extra commits (feebabc, b552839, 0c3fc73) came from and where they went. They were pushed to the PR branch by Amos, but that PR branch no longer has them. I can imagine several ways how this can happen, but I do not have enough information to pinpoint the exact sequence of events.

@eduard-bagdasaryan, can GitHub history tell us why/when those commits _disappeared_ from the v5-acl-docs branch?

@yadij, do you remember what you where doing with changes shown by feebabc and b552839? They do not appear on any of your public branches AFAICT, but I hope you can recall what (private) branch they belong to and what you were doing when you have created them. Your recollection may explain what exactly happened. Please see my previous comment for timestamps and note that these two commits may have different SHAs in your private branch if you were rebasing or otherwise altering branches history.

**Comment by eduard-bagdasaryan** [comment]
> can GitHub history tell us why/when those commits disappeared from the v5-acl-docs branch

Yes, it is possible. Obviously, there is one way to delete commits from the history: reset with '--hard' and force pushing. Here is the event for such force push for v5-acl-docs branch:

```
{
    "id": "7610009525",
    "type": "PushEvent",
    "actor": {
      "id": 9123754,
      "login": "yadij",
      "display_login": "yadij",
      "gravatar_id": "",
      "url": "https://api.github.com/users/yadij",
      "avatar_url": "https://avatars.githubusercontent.com/u/9123754?"
    },
    "repo": {
      "id": 97826891,
      "name": "yadij/squid",
      "url": "https://api.github.com/repos/yadij/squid"
    },
    "payload": {
      "push_id": 2529077002,
      "size": 0,
      "distinct_size": 0,
      "ref": "refs/heads/v5-acl-docs",
      "head": "b003ced70fa5307142a54189bf12c66884d6e049",
      "before": "0c3fc73c89f99ce8e36eb3b56bcde7e4a97a5980",
      "commits": [

      ]
    },
    "public": true,
    "created_at": "2018-05-01T04:57:17Z"
  },
```

The 'head' commit after this operation is b003ced, i.e. moved three commits back.

**Comment by rousskov** [comment]
I added the delete event to the earlier human-friendly summary. I hope this additional/last timestamped event will allow Amos to reconstruct the missing pieces of this puzzle.

**Comment by rousskov** [comment]
> we need to pay attention on the following: if we close a PR and remove some commits and force-push that branch, the PR will still have those commits

Yes, we need to keep that in mind when troubleshooting future problems. Also, GitHub might even purge those orphaned (not belonging to any branch) commits from the repository eventually. On the other hand, this is unlikely to affect day-to-day operations because nobody usually cares about closed PRs.

**Comment by yadij** [comment]
That was my first suspicion, of that case happening to the auto branch Anubis re-uses. If so it would also affect the vN-next-backports and maintenance-NN branches the squidadm uses. I'm happy that we have no sign of issues from them.

> @yadij, do you remember what you where doing with changes shown by feebabc and b552839?
> They do not appear on any of your public branches AFAICT, but I hope you can recall what (private)
> branch they belong to

feebabc and b552839 looks like the prep for this bug branch. Setting up the bug replication before trying code changes. So they should have been in this PR branch if published, or v5-bug4847 which is long gone.

FTR: "id": "7610009525", "created_at": "2018-05-01T04:57:17Z" was me pushing my copy of the v5-acl-docs branch back to github so you could see the commit order I have here (github was then showing the branch as no longer existing in yadij repo, same as with PR193 today).

**Pull request closed without merging**
