### PR TITLE
Improve handling of Gopher responses

### PR DESCRIPTION
**Pull request by MegaManSec**

### CODE REVIEW

**Comment by kinkie** [comment]
ok to test

**Review by yadij — APPROVED** [review]

**Comment by yadij** [comment]
@rousskov requesting your review for fasttrack. I know you have already reviewed this elsewhere.

**Review by kinkie — APPROVED** [review]
I'm not @rousskov but looks good enough to me :)

**Comment by rousskov** [comment]
I removed the period from the PR title. The PR is on the fast track to be merged soon.

**Pull request closed without merging**
