### PR TITLE
Add --with-systemdsystemunitdir configure option

### PR DESCRIPTION
**Pull request by marcosfrm**

### CODE REVIEW

**Comment by marcosfrm** [comment]
`--with-systemd-unitdir` is probably a better name.

**Comment by rousskov** [comment]
I would use `--with-systemd-service-file` or similar. What you are enabling here is the installation of the service file (or whatever that thing is called). The `dir` part is just a minor technical detail (where to install the service file).

Please do not misinterpret my comment as a vote for or against this PR. I do not know enough about system administration in general and Squid service file in particular to judge whether the latter is suitable for "as is" installation.

**Comment by rousskov** [comment]
OK to test

**Comment by yadij** [comment]
I don't think we can (nor should) do this. Squid has to support more OS than just systemd Linux.  squid.service installation involves many actions package builders have to perform specific to the OS environment Squid is being build for. We already distribute the file and they install as, when, and where needed.

If we were to install it automatically:

 * There are *two* systemd locations that have to be installed and which one depends on whether Squid is being built as a system service or a multi-tenanted service. The systemd.pc provides two separate variables for those locations. We would require ./configure magic to parse --prefix and related path options to determine whether the paths are installing Squid for as per-user service or system daemon - the two are not compatible in systemd's world.

 * The .service file also needs internal changes to match the build environment install parameters ./configure is called with (--prefix etc).

 * The Squid default install locations are actually BSD based - making them incompatible with systemd paths in the .service file. We may have to change the well-known Squid default locations for systemd  compatibility.

 * this PR is missing additional Makefile.am lines necessary to avoid breaking "distcheck", and for automake explicitly calling autoreconf with systemd-specific parameters involving the custom systemd variables which this patch is setting.

**Comment by marcosfrm** [comment]
> If we were to install it automatically:

The patch does not install it automatically.

> There are two systemd locations that have to be installed and which one depends on whether Squid is being built as a system service or a multi-tenanted service. The systemd.pc provides two separate variables for those locations. We would require ./configure magic to parse --prefix and related path options to determine whether the paths are installing Squid for as per-user service or system daemon - the two are not compatible in systemd's world.

The patch specifically query the "system" directory. Assuming running per-user squid makes sense, I think this kind of setup should be left to users/packagers.

> The .service file also needs internal changes to match the build environment install parameters ./configure is called with (--prefix etc).

Yes, it needs fixing.

> The Squid default install locations are actually BSD based - making them incompatible with systemd paths in the .service file. We may have to change the well-known Squid default locations for systemd compatibility.

Adjust squid.service is enough, no?

> this PR is missing additional Makefile.am lines necessary to avoid breaking "distcheck", and for automake explicitly calling autoreconf with systemd-specific parameters involving the custom systemd variables which this patch is setting.

Help appreciated.

**Comment by yadij** [comment]
> The patch does not install it automatically.

Then what is the point of this PR?  the demo .service file is already packaged up and distributed. We do not need to know where the .service install location is going to be unless it is actually being installed by our code.

> 
> Amos: The Squid default install locations are actually BSD based - making them incompatible with systemd paths in the .service file. We may have to change the well-known Squid default locations for systemd compatibility.
> 
> Marcos: Adjust squid.service is enough, no?

No. Only adjusting the .service to use the Squid defaults (ie be generated from ./configure path parameters) would result in the systemd components being installed into a BSD filesystem layout by default. systemd is explicitly and by design incompatible with non-Linux layouts. We have to switch the Squid defaults to be Linux FHS layout for a generated .service (from Squid defaults) to be compliant with systemd requirements.
 The alternative is to hard-code the expected Linux FHS paths into the .service. Which is the current situation.

> 
>  Amos:   this PR is missing additional Makefile.am lines necessary to avoid breaking "distcheck", and for automake explicitly calling autoreconf with systemd-specific parameters involving the custom systemd variables which this patch is setting.
> 
> Marcos: Help appreciated.

According to the systemd documentation the top level Makefile needs a line that calls the rpm packaging tool with a command line parameter to pass it the $systemdsystemunitdir_DATA value. You see the problem for non-RPM environments?
 All of this looks like fluff for RPM packagers which can already just pickup the .service file from its location in our sources and do whatever they need, up to and including calling pkg-config for locations where to put it.

**Comment by yadij** [comment]
yes,  foo_DATA lists the data files to automatically install when the associated foo target is being installed. There is no systemdsystemunitdir target/executable in Squid Makefiles. As you said:

> The patch does not install it automatically.

The RPM connection does something unspecified to build the systemd target(s) necessary to trigger the automake logic to install the systemdsystemunitdir_DATA files. If it was sane that would be "make install-systemdsystemunitdir", but lack of a target in the top Makefile is a strong sign that its doing something more complex.
 So even the part we can see and understand it looks like just a very convoluted way to run "/bin/install tools/systemd/squid.service /some/install/path/squid.service".

The use of ENABLE_* macro appears to be just to prevent RPM builds (or anything building the magic target) doing anything in regards to install of systemd files. Non-RPM builds wont have the magic callback part that tries to run/install the special target. So the ./configure option will not work for other builds even if the builder tries to use it.

**Comment by marcosfrm** [comment]
You convinced me.

**Pull request closed without merging**
