### PR TITLE
Maintenance: Copyright update for 2019

### PR DESCRIPTION
**Pull request by squidadm**
Fully automated update of all copyright statements to indicate
the current year as 2019.

### CODE REVIEW

**Comment by yadij** [comment]
OK to test

**Comment by yadij** [comment]
(miss-click on the comment button sorry)

**Comment by yadij** [comment]
... apparently just waiting was not sufficient.

@eduard-bagdasaryan can you please check the Anubis is okay and not confused after the mishap earlier? The Jenkins tests finished some days ago, all checks were green and the status as you see above was still waiting after 11 days.

**Comment by eduard-bagdasaryan** [comment]
> The Jenkins tests finished some days ago,

No, the tests have not fully finished for 3e68cc9 staged commit: it lacks Jenkins test results. I suspect that Jenkins was down when Anubis created this commit, that is why it could not finish the merge.

**Comment by yadij** [comment]
Okay. I will try the Jenkins "retest" button if this happens again. Thank you for checking.

**Pull request merged**
