### PR TITLE
Fix stack-based buffer-overflow when parsing SNMP messages

### PR DESCRIPTION
**Pull request by flozilla**
Fortunately, this off-by-one bug seems to have no runtime effect.

### CODE REVIEW

**Comment by rousskov** [comment]
OK to test

**Comment by yadij** [comment]
One thing to keep in mind is that this is a third-party library (from net-snmp) that we have imported wholesale long ago. Long-term we should really be removing this copy entirely and relying on distros to have the net-snmp tools which are needed anyway when the admin/users want these features.

Redesigning the way snmplib works or its API/ABI behaviour moves us further away from being able to do that switch. Not to say changes are impossible, just limit the scope to minimize the diff from net-snmp code.

**Comment by rousskov** [comment]
FWIW, the path I am advocating for does not involve redesigning the way snmplib works or its API/ABI behavior.

**Comment by flozilla** [comment]
I changed the bugfix according to the path advocated by rousskov.

**Pull request closed without merging**
