### PR TITLE
Remove unused Ftp::Gateway::printfReplyBody()

### PR DESCRIPTION
**Pull request by eduard-bagdasaryan**
Ftp::Gateway::printfReplyBody() has been unused since 0477a07.

### CODE REVIEW

**Review by rousskov — APPROVED** [review]

**Review by yadij — APPROVED** [review]

**Comment by rousskov** [comment]
FYI: I labeled this PR and PR 1276 with `S-waiting-for-QA` because some GitHub and/or Jenkins action is needed to rectify various  Jenkins failures these (and, AFAICT, other cleared) PRs are suffering from. FWIW, I do not want to try to reload Jenkins matrix or retry the failed tests now because there is another PR waiting for the not-yet-failed Jenkins tests, and I do not want to diminish that PR chances (also my attempts to do that in the past resulted in successful tests that were not reported by Jenkins to GitHub anyway).

**Comment by kinkie** [comment]
> FYI: I labeled this PR and PR 1276 with `S-waiting-for-QA` because some GitHub and/or Jenkins action is needed to rectify various Jenkins failures these (and, AFAICT, other cleared) PRs are suffering from. FWIW, I do not want to try to reload Jenkins matrix or retry the failed tests now because there is another PR waiting for the not-yet-failed Jenkins tests, and I do not want to diminish that PR chances (also my attempts to do that in the past resulted in successful tests that were not reported by Jenkins to GitHub anyway).

I hope that jenkins instability is now fixed. I have changed internet provider and there were some teething problems. Feel free to retry now.

**Comment by rousskov** [comment]
> I hope that jenkins instability is now fixed. I have changed internet provider and there were some teething problems. Feel free to retry now.

I clicked the "reload matrix" button for a few PRs (not this one) with failed Jenkins tests. I did not see the desired effect shortly after that click, and it would be difficult (for me) to track the long-term results of that reload because some of those PRs also got new manual "merge master into PR" commits now. FWIW, nothing I have seen so far contradicts my previously [discussed](https://github.com/squid-cache/squid/pull/1236#issuecomment-1384305860) belief that "reload matrix" does not update GitHub status check in some cases (and, hence, simply wastes Jenkins resources and time).

**Comment by yadij** [comment]
What "desired effects" were you looking for?

I do not see any "reload matrix" button on failed builds.  Do you mean the "Matrix Reloaded" sub-menu above that?
OR, the "Retry" button in the left-side menu of the failed matrix build attempt? [that retry is what I use]

**Comment by rousskov** [comment]
> What "desired effects" were you looking for?

GitHub status check updated from "red/failed" to "yellow/pending" (and then to "green/success"). See previous [discussion](https://github.com/squid-cache/squid/pull/1236#issuecomment-1384305860) for details, including Jenkins log quotes.

The actual effect was no updates at all AFAICT.
 
> I do not see any "reload matrix" button on failed builds. Do you mean the "Matrix Reloaded" sub-menu above that? 

Yes, the "Matrix Reloaded" button (which opens up a dialog where I select which tests to rerun and click the "rebuild matrix" button).

> OR, the "Retry" button in the left-side menu of the failed matrix build attempt? [that retry is what I use]

I used the "Retry" button in the past, and it did not work, and Francesco told me to use the "Matrix Reloaded" button instead. I will try the "Retry" button again the next time I see the same problem, but this is really should be tested by somebody who can understand and carefully track Jenkins changes -- pressing a button and not seeing desirable effects on GitHub is easy, but one has to understand what actions that button should have on Jenkins side and confirm that those actions are happening (and include GitHub status update steps).

And, again, the problem (and its solutions) may be specific to whether Jenkins tests a PR or a staged commit. I just do not know enough about those Jenkins features/plugins/whatever to get to the bottom of it quickly.

**Comment by rousskov** [comment]
> Amos: OR, the "Retry" button in the left-side menu of the failed matrix build attempt? [that retry is what I use]
 
> Alex: I used the "Retry" button in the past, and it did not work, and Francesco told me to use the "Matrix Reloaded" button instead. I will try the "Retry" button again the next time I see the same problem. ... And, again, the problem (and its solutions) may be specific to whether Jenkins tests a PR or a staged commit.

I just tried the "Retry" button for a previously [failed](https://build.squid-cache.org/job/5-pr-test/5200/) PR test, and it worked as expected, updating GitHub status check to "yellow/pending" (pointing to the [newly scheduled](https://build.squid-cache.org/job/5-pr-test/5224/) PR test).

I have not (recently) tried the "Retry" button for a previously failed staged commit test. Will do when I get a chance.

**Pull request closed without merging**
