### PR TITLE
Extend cache_log_message to Bug 5187 and job invalidation BUGs

### PR DESCRIPTION
**Pull request by ShmayaFrankel**
70 ERROR: Squid BUG: Job invalidated during ... that threw...
    71 ERROR: Squid BUG: Job invalidated during ...
    72 WARNING: Squid bug 5187 workaround triggered

### CODE REVIEW

**Review by rousskov — CHANGES_REQUESTED** [review]
I fixed PR title to follow Squid Project [format](https://github.com/measurement-factory/anubis/blob/master/README.md#pr-title).

> please also queue for backport to v6

I had to remove that request from the PR description because that description is used as a [commit message](https://github.com/measurement-factory/anubis/blob/master/README.md#commit-message) body. If needed, please post your request again after this PR is merged into master/v7.

**Comment by rousskov** [comment]
OK to test

**Review by rousskov — APPROVED** [review]
Thank you for polishing this up!

I have re-fixed PR description [formatting](https://github.com/measurement-factory/anubis/blob/master/README.md#pr-description), removed obvious/duplicated information (from Squid developers point of view -- the targeted audience for the future commit) from that PR description, and am approving this PR for merging.

**Review by yadij — APPROVED** [review]

**Comment by squidadm** [comment]
queued for backport to v6

**Pull request closed without merging**
