### PR TITLE
Docs: fix some spelling in ChangeLog

### PR DESCRIPTION
**Pull request by khalid586**

### CODE REVIEW

**Review by yadij — APPROVED** [review]

**Comment by yadij** [comment]
OK to test

**Review by rousskov — APPROVED** [review]
This revision of history is a yet another example supporting the idea of changing how we maintain/assemble ChangeLog.

**Comment by khalid586** [comment]
@rousskov @yadij If everything's alright then I hope the PR will be merged soon!

**Comment by rousskov** [comment]
> If everything's alright then I hope the PR will be merged soon!

Yes, this PR should be merged [automatically](https://github.com/measurement-factory/anubis/blob/master/README.md). In most cases, you do not need to do anything but wait. For example, you do not need to merge the ever-changing master branch into your PR branch (despite what GitHub "This branch is out-of-date with the base branch" message may encourage you to do).

**Comment by khalid586** [comment]
Is everything okay? It's been showing PR approval pending.

**Comment by kinkie** [comment]
> Is everything okay? It's been showing PR approval pending.

Yes. Two approvals and no blocks means that it should be merged in 2 days at most (see https://github.com/measurement-factory/anubis#voting-and-pr-approvals), modulo queueing. The project has been very active lately and our CI farm is hard pressed to keep up

**Review by kinkie — APPROVED** [review]
Thanks for contributing!

**Comment by rousskov** [comment]
> > Is everything okay? It's been showing PR approval pending.
> 
> Yes.

Agreed.

> Two approvals and no blocks means that it should be merged in 2 days at most (see https://github.com/measurement-factory/anubis#voting-and-pr-approvals), modulo queueing.

To clarify: A PR with two approvals and no blocks should be merged _after_ 2 days of waiting for objections (not "merged in 2 days _at most_"). 2 days is the _minimal_ total wait time in this case, not the _maximum_ total wait time as far as merging is concerned.

That 48 hour objections wait ended a few minutes ago. And it took Anubis a few more minutes to scan and update all PRs, including this one. All checks are green now. Eligible PRs (like this one) are staged and merged in the ascending PR number order, as detailed in Anubis [documentation](https://github.com/measurement-factory/anubis/blob/master/README.md).

> The project has been very active lately and our CI farm is hard pressed to keep up

Indeed. It may take some time, possibly a few days for this PR to merge, but it should happen automatically. There are currently no red flags to worry about AFAICT.

**Comment by khalid586** [comment]
@kinkie My PR isn't merged?

**Comment by kinkie** [comment]
> @kinkie My PR isn't merged?

Now it is; it got merged about 1 hour ago

**Comment by khalid586** [comment]
Why it is showing closed instead of merged?

**Comment by kinkie** [comment]
It is an artifact of how merging is technically implemented; you check that it has been merged by the "M-merged" tag added by anubis, and by the fact that the PR is in git log:
`* eca475512 (HEAD -> master, upstream/master) Docs: fix some spelling in ChangeLog (#1550)
`

**Comment by rousskov** [comment]
> It is an artifact of how merging is technically implemented; you check that it has been merged by the "M-merged" tag added by anubis, and by the fact that the PR is in git log: `eca475512 Docs: fix some spelling in ChangeLog (#1550)`

Francesco is right. I just want to add that this is a GitHub API limitation rather than some kind of a merging problem or bug. There is no way for us to tell GitHub that this PR was merged (when we are not merging this PR branch commits). When GitHub squashes and merges PR branch commits itself, then it probably updates some internal database. When we do essentially the same thing (from git point of view), GitHub cannot tell and does not let us inform it (AFAIK).

There are several reasons why we are doing this automatically instead of clicking GitHub buttons or enabling recently added GitHub PR automerging features, but this is not the right place to re-discuss them.

**Pull request closed without merging**
