### PR TITLE
Bug 4816: update negotiate_kerberos_auth helper protocol to v3.4

### PR DESCRIPTION
**Pull request by huaraz**
Updated negotiate_kerberos_auth to use latest helper protocol
with key=value pairs.

### CODE REVIEW

**Comment by rousskov** [comment]
Not sure why Semaphore CI has not acknowledge this yet -- it does see this PR. If nothing changes in the next few hours, we should click the `Update branch` button to tickle Semaphore CI.

**Comment by rousskov** [comment]
I am not sure how helper protocol versions are numbered, but I suggest the following PR title that should satisfy line-width [requirements](https://github.com/measurement-factory/anubis#commit-message):

`Bug 4816: update negotiate_kerberos_auth protocol to v3.4`

**Comment by yadij** [comment]
The numbering is to the minimum version of Squid where the protocol will work - ie version of Squid which changed the protocol (v2.5, v3.1, v3.4).

**Comment by eduard-bagdasaryan** [comment]
Because that was another title (changed by Amos 10 hours ago) the bot failed on:
echo -n "Bug 4816: negotiate_kerberos_auth: update to Squid 3.4 helper protocol (#196)" | wc -c
77

**Comment by rousskov** [comment]
Are you sure? I believe I saw M-failed-description for the title I used in my question, not the earlier one. Perhaps the label was stale, but the title I used was there for 10 hours. It it were acceptable, why did not the bot merge?

**Comment by eduard-bagdasaryan** [comment]
I was talking about [this](https://github.com/squid-cache/squid/pull/196#event-1609125676) message happend 10 hours ago.

**Comment by rousskov** [comment]
Ah, I see, you were talking about the message I did not ask about. So my question still stands.

**Comment by eduard-bagdasaryan** [comment]
Too long message body:

```
echo -n "Updated negotiate_kerberos_auth to use latest helper protocol with kv pairs." | wc -c
76
```

**Comment by rousskov** [comment]
Ah, I see, the description was too long.

**Pull request closed without merging**
