### PR TITLE
kerberos_ldap_group: fix encryption type for cross realm check

### PR DESCRIPTION
**Pull request by huaraz**
Newer setups require AESxxx encryption but old Crossrealm
tickets are still using RC4. Remove the use of the cached client
ticket encryption type and use the configured default list
(which must include AESxxx and RC4).

### CODE REVIEW

**Comment by rousskov** [comment]
@huaraz, please check that I got the scope of the comment correct in https://github.com/squid-cache/squid/pull/542/commits/4845628e4548856fd333cfcd74dca6a7735bb3cb

@yadij, FYI: I am not qualified to review the substance of the changes in this PR.

**Comment by huaraz** [comment]
Is there still something I have to do ?

Markus

**Comment by rousskov** [comment]
> @huaraz: Is there still something I have to do?

No, the ball is on Amos side:

> yadij added the M-cleared-for-merge label 4 hours ago

@yadij, nobody approved this PR so it cannot be merged regardless of the `M-cleared-for-merge` label. If you are happy with this PR going in, please approve it.

**Comment by rousskov** [comment]
@huaraz, BTW, in most cases, you do not need to keep merging official master into your PR branch. The merge [bot](https://github.com/measurement-factory/anubis) will do that for you when the merge becomes necessary. If you see merge conflicts reported by GitHub, then you will need to correct them, of course.

**Comment by rousskov** [comment]
According to bug [5042](https://bugs.squid-cache.org/show_bug.cgi?id=5042#c1), this PR broke build with "Heimdal as Kerberos5 library". @huaraz, if is this something you can fix, please post a pull request against master.

**Pull request closed without merging**
