### PR TITLE
Fixed harmless missing data member initialization

### PR DESCRIPTION
**Pull request by chtsanti**
Detected by Coverity Scan:
* CID 1424887:  Uninitialized members  (UNINIT_CTOR)

### CODE REVIEW

**Comment by yadij** [comment]
I don't think it is exactly harmless. If an admin does something like configuring concurrency for a validation helper that does not support it. Then this could lead to random results from that helpers lookups. A highly unlikely scenario, but a PITA for someone if it does happen.

Christos; I would rather this was done as C++11 initialization - that is just assign Helper::Unknown on the definition line instead of touching the constructor. AFAICS that field is the only one that needs explicit value assignment for C++11 so this fix would also then be the complete conversion of that class.

**Comment by rousskov** [comment]
@chtsanti, if the bug is not harmless, then please mention (in this PR description/future commit message body) when it was added to master and what its effects may be.

**Comment by kinkie** [comment]
retest this please

**Comment by chtsanti** [comment]
The bug was harmless.
The Ssl::CertValidationResponse::resultCode always initialised after the Ssl::CertValidationResponse object is created inside src/ssl/helper.cc.

**Pull request merged**
