### PR TITLE
V4 next

### PR DESCRIPTION
**Pull request by squidadm**

### CODE REVIEW

**Comment by rousskov** [comment]
OK to test

**Comment by yadij** [comment]
These PR titles are how github renders the temporary branch names for automated cherry-pick merges. It is not the commit title since these are temporary branches whose HEAD will become the next "v4.0" branch HEAD if the testing passes.

Unfortunately the only setting I can find to enable rebase merges is global for the repository, so I have been enabling it only for the few minutes it takes to do the final backport merge then disabling it again so the master branch PRs retain the restricted setting.

**Comment by rousskov** [comment]
> Unfortunately the only setting I can find to enable rebase merges is global for the repository, so I have been enabling it only for the few minutes it takes to do the final backport merge then disabling it again so the master branch PRs retain the restricted setting.

Yeah, that is what I would probably do as well. I agree that this is unfortunate. The merge bot will (eventually) handle this better.

Meanwhile, you may also have an option to (permanently) disable non-master branch protection for your own commits (and use git to commit these porting changes to non-master branches). I have not checked whether the GitHub configuration interface is flexible enough to make this work without dropping protection for the rest of us.

**Comment by rousskov** [comment]
> These PR titles are [...] not the commit title

Which makes picking good PR titles even more important IMO: If we are already doing something rather misleading and tricky (not using traditional merge commits or simple squash commits), then we should not be making things worse by using bad PR titles and empty PR descriptions. We (our our scripts) control those PR aspects and can make them easy-to-understand and informative.

**Comment by yadij** [comment]
Jenkins fail was due to build node crashing, not code related. Going ahead with this merge.

**Pull request merged**
