### PR TITLE
Fix a possible integer overflow in Ftp::Gateway

### PR DESCRIPTION
**Pull request by brozs**
A static analysis tool has discovered that const int csize,
might have overflowed before being passed to writeReplyBody().

### CODE REVIEW

**Comment by kinkie** [comment]
Thanks for looking into this!
The best way would be probably to use `auto`: the compiler knows what the actual type is,
and avoid any potential trucation.
In this case, it would select the return type of contentSize() , which is mb_size_t, which in turn is ssize_t

**Comment by brozs** [comment]
Oh right! Thanks for the feedback, I've modified the commit.

**Comment by kinkie** [comment]
ok to test

**Review by yadij — APPROVED** [review]

**Review by kinkie — APPROVED** [review]
Thanks

**Review by rousskov — APPROVED** [review]

**Comment by rousskov** [comment]
@kinkie, Jenkins tests for staged commit have [failed](https://build.squid-cache.org/job/5-pr-auto/COMPILER=gcc,OS=ubuntu-focal,label=pr-merge-builder/1823/console) [twice](https://build.squid-cache.org/job/5-pr-auto/COMPILER=gcc,OS=centos-8,label=pr-merge-builder/1831/console), for seemingly similar reasons unrelated to this PR. Would you mind checking what is going on?

**Comment by kinkie** [comment]
> @kinkie, Jenkins tests for staged commit have [failed](https://build.squid-cache.org/job/5-pr-auto/COMPILER=gcc,OS=ubuntu-focal,label=pr-merge-builder/1823/console) [twice](https://build.squid-cache.org/job/5-pr-auto/COMPILER=gcc,OS=centos-8,label=pr-merge-builder/1831/console), for seemingly similar reasons unrelated to this PR. Would you mind checking what is going on? The same issue is affecting #1646 AFAICT.

This is quite surprising; I relied for a couple of days on a DigitalOcean VM to run the builds while I was rewiring my home systems; that's the only difference.
Now the home datacenter is up and running, but I don't really know what could have caused the GCC crashes affecting the failed builds

**Comment by squidadm** [comment]
queued for backport to v6

**Pull request closed without merging**
