### PR TITLE
Removed tcp-banger* and pconn-banger tools

### PR DESCRIPTION
**Pull request by rousskov**
Authored-by: Amos Jeffries <squid3@treenet.co.nz>

We do not have enough resources/demand for maintaining these tools, they
do require maintenance, and there are better tools available.

* tcp-banger2 is not built by default and probably could not be built at
  all since at least 2006 commit 5679212.

* tcp-banger3 lacked build rules since inception (1998 commit 2742510)
  and probably could not be built manually (by mimicking tcp-banger2
  build commands) without warnings since 2002 commit 88d8a2a.

* pconn-banger lacked build rules since inception (1997 commit eb5f55b)
  and probably could not be built manually since at least 2007 commit
  cc192b5.

* tcp-banger.pl has portability and code quality issues; its basic
  functionality is supported by squidclient, wget, curl, and others.

Co-authored-by: Alex Rousskov <rousskov@measurement-factory.com>

### CODE REVIEW

**Comment by rousskov** [comment]
This PR contains, in part, #934 changes by Amos, and I added the corresponding `Authored-by` header that will be converted to the official commit author if this PR is merged. I listed Amos as the primary author to avoid implying that this PR, as a whole, is my original work. @yadij, please adjust as needed.

In addition to Amos' work, I removed the pconn-banger tool and wrote a new PR description from scratch. I added myself as a co-author to avoid implying that Amos is responsible for these two items. I am happy to remove that `Co-authred-by` footer if anybody wants me to!

Amos closed #934 because ([AFAICT](https://github.com/squid-cache/squid/pull/934#issuecomment-974672606)) he wanted a different PR description and did not want to keep editing it until we can find the wording we both can agree on. Hopefully, this PR description is good enough to be merged (or can be adjusted to become such).

**Review by kinkie — APPROVED** [review]
Good idea

**Comment by rousskov** [comment]
@kinkie, if I am reading Jenkins [log](https://build.squid-cache.org/job/5-pr-auto/COMPILER=gcc,OS=centos-8,label=docker-build-host/1381/consoleFull) correctly, this PR got stuck because one of the Jenkins tests timed out but did not fail in a way that GitHub can notice AND did not restart in a way that GitHub can notice. GitHub state may change by the time you read this, but the current state is waiting for an "in-progress" build 1381 (with all other builds/checks already green). That build was aborted long time ago.  I do not know why the test timed out at the very end, but I am guessing that, after that timeout, Jenkins set the check status of an already aborted/failed test to "pending", making things a lot worse.

```
14:00:25 Started by upstream project "[5-pr-auto](https://build.squid-cache.org/job/5-pr-auto/)" build number [1381](https://build.squid-cache.org/job/5-pr-auto/1381)
...
14:45:19 test -z "" || rm -f 
19:45:19 Scheduled restart of the build (up to 1 times).
19:45:19 Build timed out (after 300 minutes). Marking the build as aborted.
19:45:19 [Set GitHub commit status (universal)] PENDING on repos [GHRepository@...] (sha:647f6f5) with context:Jenkins(build test) centos-8,gcc
19:45:19 Setting commit status on GitHub for https://github.com/squid-cache/squid/commit/647f6f5e4bbf2cc9c4d2069b90ecbd39fe3ac2d9
```

If you can improve Jenmkins-GitHub integration, please do. Please reach out to @eduard-bagdasaryan if you need his assistance. This and similar integration problems add days to CI total turnaround times.

Meanwhile, I will touch PR code to restart all tests for this PR (which will probably trigger staging of other, earlier PRs).  IIRC, "reloading the matrix" does not help due to same poor GitHub integration -- when one "reloads the matrix", a new set of tests is launched, but GitHub does not see that Jenkins is rerunning this PR tests.

**Comment by kinkie** [comment]
> @kinkie, if I am reading Jenkins [log](https://build.squid-cache.org/job/5-pr-auto/COMPILER=gcc,OS=centos-8,label=docker-build-host/1381/consoleFull) correctly, this PR got stuck because one of the Jenkins tests timed out but did not fail in a way that GitHub can notice AND did not restart in a way that GitHub can notice. GitHub state may change by the time you read this, but the current state is waiting for an "in-progress" build 1381 (with all other builds/checks already green). That build was aborted long time ago. I do not know why the test timed out at the very end, but I am guessing that, after that timeout, Jenkins set the check status of an already aborted/failed test to "pending", making things a lot worse.

It's a timeout I added because sometimes thing would get stuck and Jenkins not notice, so I preferred to cleanly abort.


> 
> ```
> 14:00:25 Started by upstream project "[5-pr-auto](https://build.squid-cache.org/job/5-pr-auto/)" build number [1381](https://build.squid-cache.org/job/5-pr-auto/1381)
> ...
> 14:45:19 test -z "" || rm -f 
> 19:45:19 Scheduled restart of the build (up to 1 times).
> 19:45:19 Build timed out (after 300 minutes). Marking the build as aborted.
> 19:45:19 [Set GitHub commit status (universal)] PENDING on repos [GHRepository@...] (sha:647f6f5) with context:Jenkins(build test) centos-8,gcc
> 19:45:19 Setting commit status on GitHub for https://github.com/squid-cache/squid/commit/647f6f5e4bbf2cc9c4d2069b90ecbd39fe3ac2d9
> ```
> 
> If you can improve Jenmkins-GitHub integration, please do. Please reach out to @eduard-bagdasaryan if you need his assistance. This and similar integration problems add days to CI total turnaround times.

On the jenkins side, the only thing I could do is remove the timeout. I can try to look into Anubis code and see if I can improve it, but Eduard is probably better positioned there.

> Meanwhile, I will touch PR code to restart all tests for this PR (which will probably trigger staging of other, earlier PRs). IIRC, "reloading the matrix" does not help due to same poor GitHub integration -- when one "reloads the matrix", a new set of tests is launched, but GitHub does not see that Jenkins is rerunning this PR tests.

Interesting, in my experience retrying the build would be picked up by GitHub. I suspect we are facing slightly different edge cases here

**Comment by rousskov** [comment]
> It's a timeout I added because sometimes thing would get stuck and Jenkins not notice, so I preferred to cleanly abort.

I am interpreting this as "we do not know why things get stuck, but abort/timeout is better than getting stuck". I agree that it is much better!

However, my comment was not about the abort itself, but about the lack of proper GitHub notification when that abort happens. The log clearly shows that Jenkins tells GitHub that the test is `PENDING` (i.e. from a human GitHub observer point of view, the test is running or "in progress").

```
19:45:19 ... Marking the build as aborted.
19:45:19 [Set GitHub commit status (universal)] PENDING on repos [GHRepository@...] (sha:647f6f5) with context:Jenkins(build test) centos-8,gcc
```

Conceptually, that is wrong IMHO: That `PENDING` [status](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#get-the-combined-status-for-a-specific-reference) should be set by the restarted test (if it restarts) instead. The correct status for the aborted test is "failure" (with the right spelling that I do not know). That status can then be changed to `PENDING` if/when the test actually restarts. This is not my area of expertise, but that is what I would expect.


> On the jenkins side, the only thing I could do is remove the timeout.

Would it be possible to fix Jenkins-to-GitHub notification instead?

Removing timeout/abort alone does not help much and, arguably, makes things a little bit worse: Right now, we see an abort in the log and can quickly tell that the test is dead. If you remove that abort, then we would need to spend a lot more time trying to figure out whether the test is still making progress and should not be killed.


> I can try to look into Anubis code and see if I can improve it

Anubis has nothing to do with any of this! Anubis is unaware of Jenkins existence. This is purely between Jenkins and GitHub (and probably about how Jenkins notifies GitHub). That is why I am asking _you_ for help...

> in my experience retrying the build would be picked up by GitHub. I suspect we are facing slightly different edge cases here

I do not know what we are facing, but I can suggest a working theory: If there are different retry outcomes indeed, then perhaps the outcome depends on the Jenkins plugin. That is, Jenkins PR tests report their status to GitHub correctly, but Jenkins staged commit tests do not. IIRC, the two classes of tests are performed by _different_ Jenkins plugins/configurations/etc. If you do not have better ideas, I will try to test this theory when Jenkins fails again for a PR test and then again for a staged commit test.

```
19:45:19 Scheduled restart of the build (up to 1 times).
```

FWIW, I see no signs that the aborted build 1381 was restarted as promised by its log; build [1382](https://build.squid-cache.org/job/5-pr-auto/1382/) is for a different PR AFAICT. However, I may be misinterpreting Jenkins logs/state. Do you see those signs?

**Pull request closed without merging**
