### PR TITLE
Moved peer*(ps_state) functions into ps_state renamed PeerSelector

### PR DESCRIPTION
**Pull request by rousskov**
No functionality changes intended (other than debug message variations).

Also polished related documentation and debug messages.

Also converted "struct _icp_common_t" into an icp_common_t class, to
make its forward declarations simple. As a side effect, removed
__cplusplus ifdefs, addressing an old TODO.

### CODE REVIEW

**Comment by rousskov** [comment]
@yadij, I am posting this work-in-progress PR to address the problem with ps_state  methods [discussed](https://github.com/squid-cache/squid/pull/112#discussion_r158943353) in merged PR #112. If you like the current changes, then I will implement the remaining (and largely mechanical) adjustments currently listed in the pr description TODOs. Those adjustments will obfuscate the meaningful part of this PR so I wanted to delay them until your initial review.

**Comment by rousskov** [comment]
> Are you intending this to be a general cleanup for the class?

I cannot give a yes/no answer: I am focusing on converting static functions into methods. Beyond that, only easy polishing of modified things is in scope. Thus, there will still be problems with this class after this RP. The biggest problem I know about is the abuse of this class by peerCountMcastPeersStart(). This PR should not try to solve that difficult problem which also blocks many other polishing changes.

> alphabetical ordering of the pre-defines in .h

Done in 92e6eb8.

> removal of redundant paremeter names in method definitions 

I found only one redundant parameter in modified/added methods. Fixed in e6fe373.

Please note that I do not consider `answer` in `allow_t answer` redundant. Similarly, I find `header` in `icp_common_t *header` useful. Both cases are special because the parameter types are poorly named.

Please let me know if I missed any other cases.

Should I proceed with noisy changes listed in the PR description TODOs?

**Comment by yadij** [comment]
There is also a FwdServer&fs and an Ip::Address ip in the Peer's electorate. If you and If you like there is also icp_opcode opcode in the icp.h

**Comment by yadij** [comment]
As for the noisy changes. sure, I up to you

**Comment by rousskov** [comment]
> There is also a FwdServer&fs and an Ip::Address ip in the Peer's electorate

handlePath() needs named arguments because the types do not make it obvious which one is the "path". It could be either. (And I do not think we should combine named and unnamed parameters in one method declaration.)

noteIp(), noteIps(), and noteLookup() method declarations are not changing so I am not polishing them. I assume that you meant those methods when you said "Peer's electorate".

> If you like there is also icp_opcode opcode in the icp.h

I do not think we should combine named and unnamed parameters in one method declaration. Most of the createMessage() method parameters need names because their types are generic.

BTW, it feels wrong to spend so much time on such an unimportant styling rule. We are spending so much time because the rule cannot be formalized -- the right thing to do is a matter of opinion in many corner cases. IMO, this styling rule should not be adopted at all because it leads to more waste than style improvements.

**Comment by rousskov** [comment]
I have completed all TODOs and removed the work-in-progress designation from the PR. Please review.

**Comment by eduard-bagdasaryan** [comment]
@yadij , we need this patch in v4, would you mind this change?
Rationale: peer_access checks in peerAllowedToUse() sometimes need ALE and cause errors:

```
ACL is used in context without an ALE state. Assuming mismatch.
```

FYI: this patch helped to fix the ALE problem in peerAllowedToUse() (master cb36505). The corresponding v4 port of that commit (96198f3) was modfied to exclude peerAllowedToUse() fix.

**Comment by yadij** [comment]
The immediate issue is that this is 700 lines of change. The stable releases have a target of no more than 100 lines per release to minimize the chances of new bugs. Something this big would need a regression of v4 into beta releases until its demonstrated stable again.

On the other hand we have reached the time of year I start looking at whether master/trunk has enough important content to branch v5 for beta releases. It may be worthwhile doing that now instead of doing betas on v4. Will do that analysis later tonight.

> Rationale: peer_access checks in peerAllowedToUse() sometimes need ALE and cause errors:
> 
> ```
> ACL is used in context without an ALE state. Assuming mismatch.
> ```

For my interest, what is the use-case where this is appearing?

**Comment by eduard-bagdasaryan** [comment]
This happens when cache_peer_access checks a cached external ACL value, which requires ALE. Also, there may be a similar error of missing HttpReply in the same context (for ACLs requiring HttpReply). Providing ALE there would help with it by means of ALE:reply.

**Comment by yadij** [comment]
I am not convinced that is enough of a need. cache_peer_access is fast-group access control - so the only reliable result is that failure will occur sometimes (or always).

I advise admin wanting external ACL helper details in fast-group access controls to use the annotation features. The request object is definitely available to cache_peer_access.

**Comment by rousskov** [comment]
You asked for a use case "for your interest". You should not asses the "need" based on that single use case! There is a bug here. As a maintainer, you can reject fixing that bug in v4, of course, but you do not need to trick developers into hurting their chances of acceptance to do that.

**Comment by yadij** [comment]
Sorry for the bad phrasing, I meant need from your/client perspective.

My main issue about this remains the size of the patch. After the v5 analysis last night (see squid-dev mail) I am thinking we are better off moving v5 toward stable releases.

**Pull request merged**
