### PR TITLE
Bump minimum required GnuTLS version to 3.4.0

### PR DESCRIPTION
**Pull request by yadij**
Commit 51e09c0 (GitHub PR #81) added GnuTLS functions available starting
with GnuTLS v3.4.0 but did not bump the ./configure check accordingly.

### CODE REVIEW

**Comment by yadij** [comment]
@rousskov, FYI: The recent changes to build node results occurs because CentOS 7 recently gained an upgrade from 3.1 to 3.3 GnuTLS and pkg-config support in the process. So it was not previously building GnuTLS at all, but now can and reveals the version discrepancy.

**Comment by rousskov** [comment]
FYI: GitHub did not tell me about this PR until you requested review. I do not know why. It usually notifies about all new PRs.

**Comment by rousskov** [comment]
> CentOS 7 recently gained an upgrade from 3.1 to 3.3 GnuTLS and pkg-config support in the process. So it was not previously building GnuTLS at all, but now can and reveals the version discrepancy.

And it will stop building GnuTLS again after this PR is committed, right? 

Do we have any Jenkins nodes with GnuTLS v3.4 or later?

**Comment by yadij** [comment]
Yes CentOS will stop building with GunuTLS again. Pretty much all OS not derived from RHEL provide newer GnuTLS versions.

**Pull request merged**
