### PR TITLE
refactor peerConnectTimeout to CachePeer::connectTimeout

### PR DESCRIPTION
**Pull request by kinkie**
Resolve a TODO in the code.

### CODE REVIEW

**Comment by kinkie** [comment]
done

**Comment by kinkie** [comment]
Thanks @rousskov !

**Comment by rousskov** [comment]
> PR has been approved, nothing to do here but wait

Actually, there _is_ something to do. You need to tell Anubis that no more changes are expected so that it can safely merge the PR. You do it by setting the purple `M-cleared-for-merge` [label](https://github.com/measurement-factory/anubis/blob/master/README.md#pull-request-labels). Sorry if I am repeating the same instructions for the fifth time.

I also deleted the new green S-waiting-for-merge label that somebody added because we already have a label for this state (and the one we have is actually _required_ to advance a PR). I marked the two requests that had the now-gone green label with `M-cleared-for-merge`.

**Comment by kinkie** [comment]
> > PR has been approved, nothing to do here but wait
> 
> Actually, there _is_ something to do. You need to tell Anubis that no more changes are expected so that it can safely merge the PR. You do it by setting the purple `M-cleared-for-merge` [label](https://github.com/measurement-factory/anubis/blob/master/README.md#pull-request-labels). Sorry if I am repeating the same instructions for the fifth time.
> 
> I also deleted the new green S-waiting-for-merge label that somebody added because we already have a label for this state (and the one we have is actually _required_ to advance a PR). I marked the two requests that had the now-gone green label with `M-cleared-for-merge`.

I created the S-waiting-for-merge label, because I wanted to signal to myself that work there was done.
I am also sorry about still not having understood the full merge procedure; unfortunately https://wiki.squid-cache.org/MergeProcedure is too generic to be enlightening (and in rereading it I noticed I missed parts of it about not rebasing, as well).

Recapping:
- once there is at least one qualified human approving (on top of author) and no objections or change requests
- if test builds succeed, ad the branch is ready for merging
- then I should manually apply the M-cleared-for-merge label?

I was under the impression that if the first two conditions were true, after the objections grace time, Anubis would take care of the latter, eventually. The process-neutral S-waiting-for-merge label was meant to signal myself that the branch in this stage.

**Comment by yadij** [comment]
The process is the same one we have had since bzr days with voting (https://wiki.squid-cache.org/MergeProcedure#Votes). When the criteria pass the M-cleared-for-merge can be set and Anubis takes over.

FWIW, I try to wait until the pr-test checks are all done before setting that cleared flag - in case there is a bug we overlooked that needs major redesign. But Anubis does pay attention to those so it is technically not necessary.

**Comment by rousskov** [comment]
> I created the S-waiting-for-merge label, because I wanted to signal to myself that work there was done.

Yes, "human work is done" is what `M-cleared-for-merge` means too.

And if you do not want to clear for merge just yet even though the human work is (almost) done, then there is our internal `S-waiting-for-committer` label. If using the latter, I recommend leaving a comment to explain what that "almost" means (i.e. why the PR has not been cleared for merging already).

Please note that "human work" includes maintaining correct PR title/description and looking over the diff. You cannot just assume that your last git command did what you wanted it to do.

> MergeProcedure is too generic

Please improve it if you can, asking good questions as needed. Anubis specifics are also [documented](https://github.com/measurement-factory/anubis/blob/master/README.md). The two should be more-or-less in sync (assuming Squid Anubis instance is correctly configured), but there are a few known problems. Please see my Board [email](http://lists.squid-cache.org/private/squid-board/2020-June/001275.html) about that.

> ... then I should manually apply the M-cleared-for-merge label?

You may apply the `M-cleared-for-merge` label as soon as (you believe that) all the human work is done to your satisfaction. To avoid "sudden merger" surprises, I recommend avoid labeling PRs with red marks, but that is just a recommendation. Remove the label immediately if you are no longer satisfied with the PR state (including when you are about to make more changes). The label gives Anubis green light to merge. There is usually some delay, but that merge may happen a lot faster than you think! Assume it may happen immediately.

Here are the things you do _not_ need to worry about, under ordinary circumstances:

* You do not need to count votes to label a PR -- Anubis does that counting for you (and adjusts the GitHub "PR approval" check accordingly). 

* You do not need to worry about keeping the branch up to date with the ever-moving master. GitHub and Anubis will do that for you if there are no merge conflicts. If there are merge conflicts, you will see them on the GitHub PR status box (and the tests will fail).

* You do not need to worry about missing a test failure. If a test fails, you will see the failures in the GitHub PR status box (or attached to the staged commit). Anubis will not merge PRs with failed tests.

* You do not need to worry about actually merging the PR. In fact, humans must not merge PRs. Anubis will merge ASAP, after checking all the preconditions.

> on top of author

Currently, automated voting [rules](https://github.com/measurement-factory/anubis#voting-and-pr-approvals) do not discriminate authors. They only discriminate regular developers (their votes do not count) from core developers (their votes do count). The PR author is presumed to vote "yes".

**Pull request closed without merging**
