### PR TITLE
4.6

### PR DESCRIPTION
**Pull request by squidadm**

### CODE REVIEW

**Comment by squidadm** [comment]
OK to test

**Comment by yadij** [comment]
OK to test

**Comment by xeron** [comment]
Before you guys merge this and release 4.6, just wanted to make sure you're aware that there're 2 bug reports claiming that #348 introduces memory leak when using ecap/icap/whatever.

https://bugs.squid-cache.org/show_bug.cgi?id=4919
https://bugs.squid-cache.org/show_bug.cgi?id=4924

**Comment by yadij** [comment]
Hmm, thank you, it looks like bug mail is not being delivered properly. Deferring this release until the situation is sorted.

**Pull request merged**
