### PR TITLE
Translatons: Fixed grammatical error in French error pages

### PR DESCRIPTION
**Pull request by wouldsmina**

### CODE REVIEW

**Comment by rousskov** [comment]
For the record, the removed non-ASCII explanation in the PR description was:

```
Rule : Le participe passé s'accorde toujours avec son sujet quand l'auxiliaire est "être".
```

**Comment by rousskov** [comment]
OK to test

**Comment by rousskov** [comment]
@eduard-bagdasaryan, please check why this PR is labeled `M-failed-other`. I fixed the description, but that seemingly triggered some other failure.

**Comment by eduard-bagdasaryan** [comment]
>  I fixed the description, but that seemingly triggered some other failure.

No, this error looks unrelated: the failure occurred when Anubis received statuses and noticed that one of the statuses lacked 'target_url' attribute. I suspect that some kind of race happened: a CI was updating status metadata while the bot requested that metadata. The error was cleared when the bot requested statuses again.

**Comment by yadij** [comment]
Clearing for merge after 10+ days with no objections.

**Pull request closed without merging**
