### PR TITLE
Bug 5148: Log %Ss of failed tunnels as TCP_TUNNEL

### PR DESCRIPTION
**Pull request by rousskov**
ERR_CONNECT_FAIL/errno=111 NONE_NONE/503 CONNECT

    TAG_NONE/503 0 CONNECT example.com:443 - HIER_NONE/- -

When Squid failed to open a TCP connection to an origin server (or
through a cache peer) while handling a CONNECT request, Squid logged %Ss
as NONE_NONE because TunnelStateData waited for a successful TCP
connection to update the log tag. That unnecessary wait (modeled after
the necessary HTTP status code wait) complicated code. Squid now logs
TCP_TUNNEL to indicate the request handling path chosen by Squid.

We already use the same "handling path" approach for most other request
status codes. For example, TCP_MISS does not mean the miss transaction
was successful. It only means that Squid satisfied the request using the
cache miss forwarding logic. Even the LOG_TCP_REFRESH_FAIL_ERR status
code does not imply that the error response was successfully forwarded
to the client; only that the request was satisfied on a particular
(albeit very detailed in this case!) handling path.

Apply the same logic to tunneling attempts blocked by miss_access. They
were also logged as NONE_NONE and are now logged as TCP_TUNNEL.

The actual outcome of a tunneling attempt can usually be determined
using %err_code/%err_detail and %>Hs logformat codes.

### CODE REVIEW

**Comment by rousskov** [comment]
FWIW, the following table illustrates access logging changes (and non-changes) for a few relevant test cases:

|test|master/v7 (9a854a6)|PR (775bb43)|
|---:|---------------|---------------|
| **CONNECT directly to a non-listening origin** | | |
| %Ss | `NONE_NONE` | `TCP_TUNNEL` |
| **CONNECT through a cache_peer to a non-listening origin** | | |
| %Ss | `TCP_TUNNEL` | `TCP_TUNNEL` |
| **CONNECT through a non-listening cache_peer** | | |
| %Ss | `NONE_NONE` | `TCP_TUNNEL` |

**Comment by yadij** [comment]
Updated title and description to mention the old Squid-3.x output this bug would show, ad reported bugzilla ID

**Review by yadij — APPROVED** [review]

**Comment by yadij** [comment]
Since this is a UI change, please update `doc/release-notes/release-6.sgml.in` section `Changes to existing directives`:
```
        <tag>logformat</tag>
...
        <p>Squid now logs <em>TCP_TUNNEL</em> with the <em>Ss</em> code when a CONNECT tunnel
           is attempted, not just on successful tunnel setup.
```

**Comment by rousskov** [comment]
> please update `doc/release-notes/release-6.sgml.in` section `Changes to existing directives`:

Done in 7e91cb5 to avoid arguing.

**Comment by rousskov** [comment]
> Updated title and description to mention the old Squid-3.x output this bug would show, ad reported bugzilla ID

FWIW, I doubt bug [5148](https://bugs.squid-cache.org/show_bug.cgi?id=5148) was about how Squid _logs_ CONNECT errors. AFAICT, it was about (avoiding/fixing) CONNECT errors themselves. However, to save time, I did _not_ undo your PR metadata edits (and am not interested in debating this further).

**Review by yadij — APPROVED** [review]

**Pull request closed without merging**
