### PR TITLE
Move WHOIS code to libclients.la

### PR DESCRIPTION
**Pull request by yadij**
No logic changes

### CODE REVIEW

**Review by kinkie — APPROVED** [review]
LGTM. Thanks!

**Review by rousskov — APPROVED** [review]
IMO, this move is a bit premature because WhoisState is not a Client child but should become one (assuming the feature is not completely removed, of course).

**Comment by yadij** [comment]
> IMO, this move is a bit premature because WhoisState is not a Client child but should become one (assuming the feature is not completely removed, of course).

That is in part why I am not including any code change in this PR. This one is about removing one more dependency from squid_SOURCES. The refactor is for later.

**Comment by kinkie** [comment]
> That is in part why I am not including any code change in this PR. This one is about removing one more dependency from squid_SOURCES. The refactor is for later.

FWIW, I fully support this move as it serves to the strategic goal to make Squid more modular

**Pull request closed without merging**
