### PR TITLE
Maintenance: update --with-ldap detection

### PR DESCRIPTION
**Pull request by yadij**

### CODE REVIEW

**Review by rousskov — COMMENTED** [review]
I do not see any problems in this PR changes, but I do not know enough to do a thorough review. I hope that the time spent previously on removing Mozilla LDAP hacks (i.e. #1710 changes that are not present in this PR) was not wasted, and there will be a followup PR dedicated to that removal.

**Review by kinkie — DISMISSED** [review]

**Review by kinkie — APPROVED** [review]
shipit

**Comment by FireBurn** [comment]
I'm having issues building Squid 7.1 on RHEL7 & RHEL8 I've raised https://bugs.squid-cache.org/show_bug.cgi?id=5513

I have a feeling it's caused by this change, but it doesn't revert cleanly

**Comment by rousskov** [comment]
> I'm having issues building Squid 7.1 on RHEL7 & RHEL8 I've raised https://bugs.squid-cache.org/show_bug.cgi?id=5513
> 
> I have a feeling it's caused by this change, but it doesn't revert cleanly

Thank you for posting a fix at #2267.

**Pull request closed without merging**
