### PR TITLE
Cleanup macros in src/defines.h

### PR DESCRIPTION
**Pull request by yadij**
Reduce compile unit dependencies on src/defines.h by moving some
src/defines.h macros to their most-relevant header.

Also remove all src/defines.h macros known to be unused.

### CODE REVIEW

**Comment by yadij** [comment]
Switching this PR away from draft so the cleanup can merge progress so far. The changes are stand-alone even though they are not reaching complete removal of defines.h yet.

**Review by rousskov — CHANGES_REQUESTED** [review]
Thank you for cleaning this up.

The PR description says "Remove unused macros". I do not think this PR removes all unused macros declared in src/defines.h. I was not sure how you decided which unused macros to remove, so I ran a dumb script, and it suggested that the following src/defines.h macros are also unused. Could you please remove those that can be easily removed and adjust the PR description accordingly?

```
SQUID_DEFINES_H
DNS_INBUF_SZ
BUF_TYPE_8K
BUF_TYPE_MALLOC
ANONYMIZER_NONE
ANONYMIZER_STANDARD
ANONYMIZER_PARANOID
IDENT_NONE
IDENT_PENDING
IDENT_DONE
MAX_MIME
HIER_MAX_DEFICIT
ICP_FLAG_HIT_OBJ
AUTHENTICATE_AV_FACTOR
NTLM_CHALLENGE_SZ
current_stacksize
MAX_CLIENT_BUF_SZ
CBIT_BIT
CBIT_BIN
MAX_FILES_PER_DIR
AUTH_MSG_SZ
VIEWINCLUDED
VIEWEXCLUDED
STORE_META_DIRTY
STORE_META_BAD
STORE_META_TLD_START
STORE_META_TLD_SIZE
SwapMetaType
SwapMetaSize
SwapMetaData
```

**Comment by rousskov** [comment]
I adjusted the PR title/description a little to be more precise. Once the situation with unused macros is clarified, the last description sentence should be adjusted to say either "all" or "some".

**Comment by yadij** [comment]
Thanks for the list. Updated the description because as stated already this is being made non-Draft due to lack of time to cleanup the entire Squid codebase in this way right now.

PS. That "dumb script" sounds like something worth adding to scripts/maintenance (with adjustments) to catch useless macros regardless of where they are in the code.

**Comment by rousskov** [comment]
> PS. That "dumb script" sounds like something worth adding to scripts/maintenance (with adjustments) to catch useless macros regardless of where they are in the code.

Unfortunately, that two-line script is too dumb to use for automation and that limitation cannot be fixed without using a completely different (smart) approach for which I lack time. Fortunately, the problem itself is very minor.

I will see whether I can quickly check the listed suspects for removal.

**Review by rousskov — APPROVED** [review]
> I will see whether I can quickly check the listed suspects for removal.

Done in branch commit 97c333e. I also adjusted the PR description.

I removed all [suspects](https://github.com/squid-cache/squid/pull/860#pullrequestreview-714268943) except CBIT_BIT() and CBIT_BIN(). Those two are only used inside src/defines.h itself, so they were wrongly flagged by the dumb script.

Please feel free to undo or adjust further as needed, of course.

**Pull request closed without merging**
