### PR TITLE
Bug 4861: HTTPMSGLOCK missing pointer safety

### PR DESCRIPTION
**Pull request by yadij**
Check that HttpMsg pointers are not nullptr before attempting to lock.

### CODE REVIEW

**Comment by yadij** [comment]
NP: This change has already been made in v5 during other changes and refactoring of the HttpMsg object hierarchy.

**Comment by rousskov** [comment]
> This change has already been made in v5

@yadij, was that v5 change reviewed? I cannot find a matching review on squid-dev.

**Comment by yadij** [comment]
I believe it was, though not standalone - addition of this if-condition was a minor change necessary to get the conversion to inline functions to be complete. In the context of raw-* vs Pointer I overlooked that it might be a bug in its own right biting these older versions.

**Comment by rousskov** [comment]
I was hoping that the decision to allow locking of an absent object was discussed/justified because it would be interesting for me to learn why such allowance is a good idea. I now assume that the justification I am looking for does not exist -- I could not find it, and your response does not point to it either.

**Comment by yadij** [comment]
Well, this is a rough implementation of reference counting. In the ref-counted model callers always just assign, the smart pointer decides if lock or unlock is needed. This implementation being not very good requires callers to always use the *[UN]LOCK() macros when assigning to their raw-ptr which handle the ref-count "internal" check(s).

Long term plan of course is to use proper ref-counted Pointer instead and delete these macros/inline.

**Comment by yadij** [comment]
I was hoping Anubis could take on this type of commit to the stable branch, but from the looks of it that currently just screws up its processing of regular master branch PR's.

**Comment by rousskov** [comment]
> I was hoping Anubis could take on this type of commit to the stable branch

Anubis merges PRs into their base branches (shown by GitHub at the top of each PR). This PR is based on the v4.0 branch. Anubis does not have a notion of branch stability.

> from the looks of it that currently just screws up its processing of regular master branch PR's.

What got screwed up? Anubis does not have any special code for the master branch AFAIK. In other words, it should not treat the master base branch any differently. There are per-base-branch voting settings IIRC, but those are not relevant here. All PRs, regardless of their base branch should be treated the same way.

**Comment by rousskov** [comment]
@eduard-bagdasaryan, please see if you can correlate @yadij description about with Anubis logs: Why did the bot get stuck "halfway through"?

**Comment by eduard-bagdasaryan** [comment]
>  Why did the bot get stuck "halfway through"

The bot got stuck because of an error: `You're not authorized to push to this branch`
We need to configure `v4.0` protection settings like it is configured for `master`. Probably some other branches need adjusting as well to avoid future questions like "this bot screws it up".

**Comment by yadij** [comment]
Ah, good to know thank you.

**Comment by rousskov** [comment]
@yadij, I will give Anubis permission to commit to v4 if that is OK with you. Doing so should resolve the "stuck on permissions" problem you have seen in this pull request. Side effect: Any core developer would be able to authorize automatic merging of a pull request into v4 without _your_ review. Needless to say, core developers should not be doing that, but there is currently no automation to support this restriction, so mistakes are possible. For example, I might add an `M-cleared-for-merge` label thinking (incorrectly) that a pull request is targeting master rather than v4.

@eduard-bagdasaryan, please file an Anubis [issue](https://github.com/measurement-factory/anubis/issues) to add support for `required reviewers`. It should be a per-branch configuration setting.

**Comment by yadij** [comment]
@rousskov, I am okay with that.

**Comment by rousskov** [comment]
Done.

Please note that neither PR Approval nor Jenkins tests are required for v4.0 commits. Anubis would still count votes and Jenkins would still run tests, of course, but GitHub would not stop anybody with enough rights from pushing the Big Green merge button. Semaphore tests are required.

However, there seems to be a problem with branches: We should be using a `v4` branch for ongoing v4 work (especially after a v4.1 release), but there is only `v4.0` available. @yadij, if you have created a v4 branch already, please check that you pushed it. 

We will need to adjust v4 permissions once that branch exists.

**Pull request merged**
