### PR TITLE
Fix libntlmauth build on current Fedora Rawhide

### PR DESCRIPTION
**Pull request by kinkie**
ntlmauth.cc:187: error: 'time' was not declared in this scope

### CODE REVIEW

**Comment by kinkie** [comment]
Error message:
../../../../lib/ntlmauth/ntlmauth.cc:187:28: error: 'time' was not declared in this scope; did you mean 'utimes'?

**Review by rousskov — APPROVED** [review]
Thank you for fixing this.

I adjusted PR title to indicate that this is a build fix, to clarify which helpers are affected, and to use a more common (in recent git log) spelling of fedora-rawhide. I also simplified the PR description and provided the error message that developers can match when reviewing git log. I do not insist on any of these adjustments. Please undo or adjust further if needed.

**Comment by kinkie** [comment]
What breaks is actually libntlmauth, which is part of the squid core. Clarified that.
I'm happy with the current status, ready for merging

**Comment by rousskov** [comment]
> What breaks is actually libntlmauth, which is part of the squid core. 

That library is used to build a few NTLM helpers. It is not really a part of Squid core. However, these details do not really matter. The current PR title is not wrong, and I am OK with it.

**Comment by kinkie** [comment]
> > What breaks is actually libntlmauth, which is part of the squid core.
> 
> That library is used to build a few NTLM helpers. It is not really a part of Squid core. However, these details do not really matter. The current PR title is not wrong, and I am OK with it.

Got you. It seemed to me it was unconditionally built; it's not, but it's built if any ntlm helper is built - the decision point is at lib/Makefile.am line 43

**Pull request closed without merging**
