### PR TITLE
log_db_daemon: Fix DSN construction

### PR DESCRIPTION
**Pull request by yadij**

### CODE REVIEW

**Review by kinkie — APPROVED** [review]
Thanks for looking into this!

**Comment by yadij** [comment]
FTR; Thanks should go to jose.rodriguez of squid-users for identifying the DSN as problematic.

**Comment by Joe1962** [comment]
> FTR; Thanks should go to jose.rodriguez of squid-users for identifying the DSN as problematic.

Thanks for the credit, just trying to be helpful.

**Review by rousskov — APPROVED** [review]

**Comment by squidadm** [comment]
queued for backport to v6

**Pull request closed without merging**
