### PR TITLE
Remove unnecessary net compatibility workarounds

### PR DESCRIPTION
**Pull request by kinkie**
All modern network stacks provide inet_ntop(), inet_pton(), getaddrinfo(), and getnameinfo() APIs.

Also removed related Solaris 9 hacks, effectively discontinuing support for that platform.
Solaris 9 is no longer supported by Oracle.

### CODE REVIEW

**Comment by kinkie** [comment]
This is a backport of commit eb9259b (PR #1404)

**Comment by rousskov** [comment]
Feels a bit odd to discontinue Solaris 9 support in the middle of stable Squid release series (without documenting why an exception should be made), but it is your and Amos call.

Should not this kind of change be mentioned in v6 release notes?

**Comment by kinkie** [comment]
> Feels a bit odd to discontinue Solaris 9 support in the middle of stable Squid release series (without documenting why an exception should be made), but it is your and Amos call.
> 
> Should not this kind of change be mentioned in v6 release notes?

That's a valid question.
Looking at current release notes, I can't find any notice ever about dropped obsolete OS support, while these are mentioned in ChangeLog.
On top of that, given that Solaris 9 EOL happened in October 2014, it's highly unlikely that anyone is affected by this change.

**Comment by rousskov** [comment]
To avoid a misunderstanding, by "this kind of change" and "discontinue Solaris 9 support", I do not mean some abstract "support" concept. I mean breaking Squid build as detailed in recent Bug [5382](https://bugs.squid-cache.org/show_bug.cgi?id=5382#c0) that triggered this PR.

IMHO, Solaris 9 folks upgrading to Squid v6 deserve to know that they will not be able to build Squid v6 on their OS. Speculations about probability of such folks existence do not appear particularly relevant because I am not asking to preserve Squid ability to build on Solaris. I am only suggesting to disclose a fairly significant change.

As for disclosure _location_, when upgrading folks [ask](https://lists.squid-cache.org/pipermail/squid-users/2024-June/026713.html) what they need to read about upgrade dangers, [we](https://lists.squid-cache.org/pipermail/squid-users/2024-June/026716.html) do not tell them to read ChangeLog. [We](https://lists.squid-cache.org/pipermail/squid-users/2024-June/026759.html) tell them to read release notes. IMO, we are saying the right words, but these words rely on our release notes reflecting changes like this one.

P.S. This merged change is not reflected in ChangeLog either.

**Pull request merged**
