### PR TITLE
Improve handling of empty lines received prior to request-line

### PR DESCRIPTION
**Pull request by Blarse**

### CODE REVIEW

**Comment by Blarse** [comment]
Attached is an example request that triggers AddressSanitizer with:

```
=================================================================
==14==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62100000d900 at pc 0x0000010b8aaa bp 0x7fff41cb4930 sp 0x7fff41cb4928
READ of size 1 at 0x62100000d900 thread T0
    #0 0x10b8aa9 in SBuf::operator[](unsigned int) const /usr/src/debug/squid-6.1/src/http/one/../../../src/sbuf/SBuf.h:242:68
    #1 0x10b8aa9 in Http::One::RequestParser::skipGarbageLines() /usr/src/debug/squid-6.1/src/http/one/RequestParser.cc:47:75
    #2 0x10c3110 in Http::One::RequestParser::doParse(SBuf const&) /usr/src/debug/squid-6.1/src/http/one/RequestParser.cc:357:9
    #3 0x10c250e in Http::One::RequestParser::parse(SBuf const&) /usr/src/debug/squid-6.1/src/http/one/RequestParser.cc:339:25
    #4 0x9da423 in ConnStateData::parseHttpRequest(RefCount<Http::One::RequestParser> const&) /usr/src/debug/squid-6.1/src/client_side.cc:1310:35
    #5 0x10608f2 in Http::One::Server::parseOneRequest() /usr/src/debug/squid-6.1/src/servers/Http1Server.cc:86:29
    #6 0x9d415a in ConnStateData::clientParseRequests() /usr/src/debug/squid-6.1/src/client_side.cc:1940:43
    #7 0x9ff61a in ConnStateData::afterClientRead() /usr/src/debug/squid-6.1/src/client_side.cc:1986:10
    #8 0x1076e6a in Server::doClientRead(CommIoCbParams const&) /usr/src/debug/squid-6.1/src/servers/Server.cc:183:5
    #9 0x107b6e1 in JobDialer<Server>::dial(AsyncCall&) /usr/src/debug/squid-6.1/src/servers/../../src/base/AsyncJobCalls.h:175:9
    #10 0x10e3d32 in AsyncCall::make() /usr/src/debug/squid-6.1/src/base/AsyncCall.cc:44:9
    #11 0x10e98a1 in AsyncCallQueue::fire() /usr/src/debug/squid-6.1/src/base/AsyncCallQueue.cc:27:15
    #12 0x755ba2 in EventLoop::dispatchCalls() /usr/src/debug/squid-6.1/src/EventLoop.cc:144:54
    #13 0x755ba2 in EventLoop::runOnce() /usr/src/debug/squid-6.1/src/EventLoop.cc:121:19
    #14 0x755414 in EventLoop::run() /usr/src/debug/squid-6.1/src/EventLoop.cc:83:13
    #15 0xbe3f74 in SquidMain(int, char**) /usr/src/debug/squid-6.1/src/main.cc:1673:14
    #16 0xbde006 in SquidMainSafe(int, char**) /usr/src/debug/squid-6.1/src/main.cc:1363:16
    #17 0xbde006 in main /usr/src/debug/squid-6.1/src/main.cc:1351:12
    #18 0x7f826c6b3e3c in __libc_start_main (/lib64/libc.so.6+0x27e3c)
    #19 0x56f929 in _start /usr/src/RPM/BUILD/glibc-2.32-alt5/csu/../sysdeps/x86_64/start.S:120

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/src/debug/squid-6.1/src/http/one/../../../src/sbuf/SBuf.h:242:68 in SBuf::operator[](unsigned int) const
Shadow bytes around the buggy address:
  0x0c427fff9ad0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c427fff9ae0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c427fff9af0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c427fff9b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c427fff9b10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c427fff9b20:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff9b30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff9b40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff9b50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff9b60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff9b70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==14==ABORTING
```

[squid-buffer-over-read.req.txt](https://github.com/squid-cache/squid/files/12550337/squid-buffer-over-read.req.txt)

**Comment by rousskov** [comment]
OK to test

**Comment by rousskov** [comment]
@Blarse, our CONTRIBUTORS-updating script cannot tell which of your commit emails it should use for the corresponding entry. You can see that script results in the "Check source-maintenance" diff inside the "Run ./test-suite/test-sources.sh" section in [CI console log](https://github.com/squid-cache/squid/actions/runs/6111993840/job/16588476492?pr=1470). Please let me know the right variation, and we will update CONTRIBUTORS manually to match your preference. Thank you.

**Comment by Blarse** [comment]
Actually I would prefer 'Egor Ignatov <egori@altlinux.org>' entry for my contributions.
Didn't even notice before that it used another email.

**Comment by yadij** [comment]
FTR; the RFC requirements behind this code have been altered slightly between RFC7230 and RFC9112. The latest specification requires that we **SHOULD** skip these garbage lines.

As such the entire `skipGarbageLines()` method should be dropped and the one caller altered to run the same logic as `skipLineTerminator(tok)` in a loop, but without the exception thrown at the end.

**Comment by rousskov** [comment]
> the RFC requirements behind this code have been altered slightly between RFC7230 and RFC9112. The latest specification requires that we **SHOULD** skip these garbage lines.

RFC 7230 also [says](https://datatracker.ietf.org/doc/html/rfc7230#section-3.5) that we SHOULD skip those lines. Our code even quotes that SHOULD requirement.

> As such the entire `skipGarbageLines()` method should be dropped and the one caller altered to run the same logic as `skipLineTerminator(tok)` in a loop, but without the exception thrown at the end.

This is a discussion for another PR, but I see no reason to drop that method -- we still need some place to put that non-trivial code/logic/documentation somewhere... However, some refactoring to remove code duplication across skipGarbageLines() and skipLineTerminator() is warranted, and that refactoring may change the set of methods we use, of course.

**Comment by rousskov** [comment]
> I would prefer 'Egor Ignatov [egori@altlinux.org](mailto:egori@altlinux.org)' entry for my contributions.

#1476 updates CONTRIBUTORS with that preferred spelling.

**Review by yadij — APPROVED** [review]

**Comment by squidadm** [comment]
queued for backport to v6

**Comment by squidadm** [comment]
queued for backport to v6

**Comment by squidadm** [comment]
queued for backport to v5

**Pull request closed without merging**
