### PR TITLE
Bug 4917: Please create tags for released versions

### PR DESCRIPTION
**Pull request by FireBurn**
I've got a bug for this but it's not been looked at since I last pointed out the tags weren't created

Lets see if I have more luck here

### CODE REVIEW

**Comment by rousskov** [comment]
> I've got a bug for this but it's not been looked at since I last pointed out the tags weren't created

Bugzilla has failed to notify me about bug [4917](https://bugs.squid-cache.org/show_bug.cgi?id=4917), but I have updated that bug report now.
 
> Lets see if I have more luck here

This PR should be closed, of course, but I wish you good luck with getting this old problem resolved!

**Comment by FireBurn** [comment]
Bumping this again. Tags shouldn't be this difficult

**Comment by yadij** [comment]
Tags exist in the release repository. https://github.com/squidadm/squid/tags

**Comment by FireBurn** [comment]
This is the first I'm hearing of https://github.com/squidadm/

**Comment by rousskov** [comment]
> Tags exist in the release repository. https://github.com/squidadm/squid/tags

@yadij, do you want me to copy those tags from that unofficial "release repository" into the official Squid repository?

**Comment by yadij** [comment]
> > Tags exist in the release repository. https://github.com/squidadm/squid/tags
> 
> @yadij, do you want me to copy those tags from that unofficial "release repository" into the official Squid Project repository (i.e. https://github.com/squid-cache/squid)?

Not sure why you are throwing around "official" and "unofficial". Squid has always had separate repositories for public development access, and for internal release management. Although if one is not dealing directly with the intimacies of how releases are made the latter may not be obvious.

 https://github.com/squid-cache is an account created by yourself[1] and maintained by Measurement Factory software. Use is primarily for developer access and submissions to Squid.

 https://github.com/squidadm is the account created to mirror publicly the release repository run out of The Squid Software Foundation master.squid-cache.org server.

If you want to sync up the tags, feel free to do so. Like I said last time, if you allow the squidadm account push access to "squid-cache/squid" repository the master server automation can push them on releases.

**Comment by rousskov** [comment]
> Not sure why you are throwing around "official" and "unofficial".

I am using the best description I know.

> Squid has always had separate repositories for public development access, and for internal release management. Although if one is not dealing directly with the intimacies of how releases are made the latter may not be obvious.

While the release manager may use whatever repositories they want, such use does not make those repositories official. The tags @FireBurn is asking for belong to the official Squid repository (i.e. https://github.com/squid-cache/squid). Their presence elsewhere does not solve the problem. If anything, it only makes it worse by increasing confusion among Squid users.

> https://github.com/squid-cache is an account created by yourself[1] and maintained by Measurement Factory software. Use is primarily for developer access and submissions to Squid.

The "creator" of the official Squid organization account does not matter -- somebody or something has to create each GitHub account. What matters is that this account belongs to the Squid Project. It is maintained by the Squid Project (all of us), using various software and manual efforts. The official Squid repository (i.e. https://github.com/squid-cache/squid) is the repository that anybody looking for Squid sources (and their metadata) should use. It is missing release tags, for no good reason.
 
> if you allow the squidadm account push access to "squid-cache/squid" repository the master server automation can push them on releases.

Why are you taking about _me_ allowing that access?! You can allow it yourself (if you insist it is required). We have equal repository management rights, and I am not vetoing this specific repository change. I think there are better ways to manage tagging (as we have discussed elsewhere), but I am not stopping you from giving squidadm access rights for the purpose of adding tags to the official repository. You can even give those rights temporary, while the tags are updated!

> If you want to sync up the tags, feel free to do so.

I do not want to (do someone else's job), but if you ask me to do it, I will. As an official v5 maintainer, you are in the driving seat as far as v5 tags are concerned. AFAIK, you have not asked me to "sync up the tags". The ball is still on your side.

**Pull request closed without merging**
